### ISSUE TITLE
*BSD Support

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/fetch#10]
### *BSD Support

This issue is to report what works and doesn't work with the script on OpenBSD. This is a checklist of BSD distros and whether or not the script works/supports them.

- [X] FreeBSD
- [X] OpenBSD
- [X] NetBSD
- [ ] DragonFlyBSD
    - I'm having trouble getting this to work in a virtual machine.
- [ ] PC-BSD 
    - This will take me 3 hours to download so don't expect it soon.

If you're running any of the unchecked distros above I'd love it if you could test out the newest master.

**NOTE: If there's no interest for any of the unchecked distros I won't be in any sort of rush to add support for them.**

**Comment by dylanaraps** [comment]
If no one is willing to help me test then I won't add support.

**Comment by dylanaraps** [comment]
We first need to detect which BSD version the user is running.

What's the output of these commands?

```sh
cat /etc/*version
cat /proc/version
cat /etc/*release
uname -rv
```

**Comment by dylanaraps** [comment]
I've pushed a commit with *BSD support, It's untested, experimental and fairly feature complete.

**Comment by dylanaraps** [comment]
This is a checklist of BSD distros and whether or not the script works with them.

- [X] FreeBSD
- [ ] OpenBSD
- [ ] NetBSD
- [ ] DragonFlyBSD

If you're running any of the unchecked distros above I'd love it if you could test out the newest master.

**Comment by dylanaraps** [comment]
If you're using DragonFlyBSD or PC-BSD then open another issue.

**Comment by ix** [comment]
Thing is, if you want *BSD users to use your script, you probably shouldn't be using bash and instead using POSIX sh.

*BSD doesn't ship with bash and most users dislike it.

**Comment by dylanaraps** [comment]
If a BSD user wants to use my script then they'll have to install bash, if they won't then bad luck. I'm not rewriting the script to support POSIX sh and besides Screenfetch also depends on bash so I don't see this as an issue at all.
