### ISSUE TITLE
Image Disappearing

### ISSUE THREAD

**Issue by rushsteve1** [dylanaraps/fetch#105]
The image of the wallpaper disappears when GNOME Terminal. When running Fetch the image appears then immediately disappears immediately. On rare occasions the image does display correctly, but when the terminal window loses focus disappears.

Debian Testing
Bash: 4.3.42
Linux: 4.3.0-1-amd64
GNOME Terminal: 3.18.2

[WebM Example](https://my.mixtape.moe/zoqmsu.webm)

**Comment by qualious** [comment]
Well, dylan presumably fixed this as seen in here #18 .

But, the issue itself is related to w3m and vte based terminals iirc, you can recreate this behavior with switching workspaces/losing focus in ranger(cli file manager that uses w3m) too.

**Comment by dylanaraps** [comment]
This is a w3m issue and there's nothing I can do about it.

**Comment by klyberess** [comment]
A similar issue occurs when starting neofetch like so: urxvt -hold -e neofetch. Is there a workaround?

**Comment by klyberess** [comment]
I'm using an xft font (inconsolata). [Here's](https://my.mixtape.moe/hxguyy.png) an example (excuse the size). Above: just "neofetch" from urxvt. Below: "urxvt -hold -e neofetch", also from a urxvt terminal. I've tried various images and image formats, too.

It's quite possibly my mistake, but if it is, I'm too dumb to see it.

**Comment by dylanaraps** [comment]
I can reproduce this on my laptop, so I'll work on fixing this now.

**Comment by klyberess** [comment]
Great, thanks. I appreciate your work.

**Comment by dylanaraps** [comment]
@klyberess, I can't find a fix for this. This seems to be a w3m-img/URxvt issue and not a neofetch one. There's really nothing I can do to fix this unfortunately.

**Comment by klyberess** [comment]
All right, thanks for trying. It's just a minor annoyance, not a dealbreaker.
