### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by xDemonessx** [dylanaraps/fetch#12]
using getos, we can add:

        "Windows")
            distro="$(systeminfo | sed -n 's/^OS Name:[[:blank:]]*//p')"

to print the version. Uptime and other statistics can then further be added from the flag by default.

**Comment by dylanaraps** [comment]
Windows support is actually almost done in my local repo. It'll be finished very soon.

**Comment by dylanaraps** [comment]
Do you mean Windows support or CYGWIN support?

**Comment by xDemonessx** [comment]
Figures! You've been working very fast... thanks! It works, side from the odd window focus causing the image to disappear from the terminal. In this instance, I was using cygwin.

**Comment by dylanaraps** [comment]
What terminal emulator did you get the flicker in? There's a flicker issue with vte based terminals that I've been trying to fix.

**Comment by xDemonessx** [comment]
urxvt - the images wont display in mintty, and I haven't troubleshooted it any. I can test and look into it since I'm probably just missing something in my .minttyrc

**Comment by dylanaraps** [comment]
I'll boot up my windows vm and work on it now.

**Comment by dylanaraps** [comment]
Alright.

The only info we're missing now is cpu and memory.

**Comment by dylanaraps** [comment]
Everything but images should work now.

I'd like you to test if that's alright.

**Comment by dylanaraps** [comment]
I can't get the images to load in mintty either. I'm installing X11 and Urxvt now to test.

**Comment by xDemonessx** [comment]
![gilliamii_2016-01-05_55](https://cloud.githubusercontent.com/assets/3487603/12109178/33bd142a-b345-11e5-8238-1bc32bd39ab4.png)

Memory works, OS is a bit vague - uptime isn't working though the code looks ok at a glance. I will have time to test more and look into it tomorrow. I will note i am of course manually using an image with the --image and --size flags since it just wont work any other way right now. It is possible to point it to the active wallpaper in use by pointing to %AppData%\Microsoft\Windows\Themes\TranscodedWallpaper.jpg", but this image is sometimes displayed weird based on monitor position/if its set to tiled/center/what not.

**Comment by dylanaraps** [comment]
Thanks for testing! 

- I'll add Windows version detection (XP/Vista/7/8/10)

- You seem to be missing the ```uptime``` command, my Cygwin has it.

- I'll add an option to use the wallpaper on windows. 

- You can use the flag ```--font_width num``` to size the image correctly. Try setting it to a 7.

- Once you set ```--font_width``` you can use the flag ```--split_size num`` to change how large the image will be. A value of 3 makes the image and text take up a third of the terminal width each,  a value of 4 makes the image and text take up a quarter of the width each and etc.

Thanks for testing!

**Comment by dylanaraps** [comment]
One more thing, what does this output on your system?

```cmd /c ver```

**Comment by dylanaraps** [comment]
I've tested the script in both Windows XP and 7 and it seems to be working without issues now. I still can't get images to work in Mintty but they work just fine inside urxvt etc.

If you're having any issues or any ideas let me know.

**Comment by xDemonessx** [comment]
Thanks for the information on the missing procps package. 
Here is the cmd /c ver result:
![gilliamii_2016-01-06_12](https://cloud.githubusercontent.com/assets/3487603/12159560/f0b87132-b4a8-11e5-8e88-6e59edc2e187.png)

Default result (no flags):
![gilliamii_2016-01-06_45](https://cloud.githubusercontent.com/assets/3487603/12159708/30b75ce8-b4aa-11e5-9bfd-b87642bf07d7.png)

Suggested font spacing flags:
![gilliamii_2016-01-06_39](https://cloud.githubusercontent.com/assets/3487603/12159726/6918b910-b4aa-11e5-9102-abea781bf09a.png)

Issues: Dual monitor wallpapers won't display properly, as you can see. Unfortunately, I can't think of a solution that would work for dual monitors - unless there's some registry somewhere that shows a wallpaper from the primary monitor only that I am not aware of. Unless you detect a second monitor for windows specifically, and offset the crop to the image it won't work. Even then, the transcoded wallpaper is weird and it probably just won't ever work with two displays (unless of course, its one solid wallpaper and not two weird offset ones like my unique display). Either way, I personally don't believe it will be a huge issue to the majority of windows users as my displays are retarded.

Suggestions:
Alternate shell display. Searching for blackbox, litestep, and other foreign processes that may be running to give a more accurate read on what is actually effecting visual display and theming on Windows.

You are already probably working on some of this as well:

Things like Kernel, and packages, unfortunately may not be relevant for a fetch on windows. You can replace or offer a field with either a "Music" player, or "IRC/Chat" client fields. Primarily, the windows theme is pretty much always applicable  and should replace any GTK theme field.  All of these are found pretty easily, but it may slow down your script. Having them within the script by default, then just allowing someone to choose what to display from a list would make it easier to use rather than multiple flags and echo/print lines.

I really do appreciate the ability to customize the script with the custom echo/print lines however as you can keep speed while getting the result you want. Result of modifying the script itself:
![gilliamii_2016-01-06_02](https://cloud.githubusercontent.com/assets/3487603/12160527/86e1427a-b4b2-11e5-887a-39c31fef69ed.png)

It would be great to see the "scrot"option actually take a screenshot, and have it save to desktop/choice directory.

**Comment by dylanaraps** [comment]
Thanks for the writeup!

- I have an idea about how to fix the wallpaper issue. (It'll be another crop mode you can use.)
    - Actually have you tried ```--crop_mode fit/fill```? They may solve the issue.

- The font spacing flag needs to be set to your exact font width otherwise you'll have a huge gap between text/image. 

- Adding extra functions shouldn't slow down the script at all unless they're executed. I'll add some more functions to get windows specific data (Shell, Visual Style, etc) but they'll be off by default.
    - Searching for running processes is really slow. I'll do some digging and see if there's a viable alternative to that.

- A scrot option should be easy to add as well. 

Thanks for the feedback! 

I'll get to work.

**Comment by dylanaraps** [comment]
It'd be really helpful if you could also make a list of the commands you're using to output the Icons, Shell etc. :)

**Comment by dylanaraps** [comment]
I've added a function to get the current visual style. (getvisualstyle) 

I've tested it in a Windows 7 vm and it seems to work fine. Let me know if there are any issues with it.

**Comment by xDemonessx** [comment]
The icons line was added with just "echo Icons:" and typing it out. Since icons are controlled via imageres.dll, theres no way to really tell what iconpack you have install. Everything else was pulled from the tasklist.

Crop mode fit/fill dont really fix it, fill is probably the best result as at least it centers the image better.

I use autohotkey with irfanview to take screencaps: http://pastebin.com/raw/JTwRtuQy

**Comment by dylanaraps** [comment]
Thanks, does the visual style function work? Just add ```Title Here: getvisualstyle``` to the array at the top.

Also are you able to upload that full Windows wallpaper file? (The one in the first two screenshots) I want to use it to create a new crop mode.

**Comment by xDemonessx** [comment]
![transcodedwallpaper](https://cloud.githubusercontent.com/assets/3487603/12163727/9bc464c4-b4d5-11e5-9de9-ec1191b3777b.jpg)

I'm actually using multiwall to set it, so when it generates the image it comes out this strange way - i have one monitor sitting higher than the other.

After testing, getvisualstyle isn't giving the full name of the visual style, it just says "custom".

**Comment by dylanaraps** [comment]
Custom is the default name for unamed themes on Windows iirc. 

How are you setting the themes and are they named?

**Comment by xDemonessx** [comment]
Good thinking. I do normally set them directly within Ave Style builder, which names the .msstyle and will show in the fetch properly. However I have been adjusting the window options (border and captions) recently within the personalization panel, and so the theme was showing as "unsaved". So yes, it will read the theme name as displayed in "Personalization"

**Comment by xDemonessx** [comment]
One more thing, is it possible for the script to randomly choose an image from a directory?

**Comment by dylanaraps** [comment]
That's a great idea!

Will do.

**Comment by dylanaraps** [comment]
Image shuffling is in master now.

**Comment by dylanaraps** [comment]
I installed multiwall and did some digging, what does the image stored here look like?

```
C:/Users/USER/AppData/Roaming/MultiWall/wallpaper.bmp
```

I'm hoping that that's the wallpaper pre-jumble.

**Comment by dylanaraps** [comment]
I'm a little stuck with trying to figure out how to get any other info on Windows without checking currently running processes against an array, the script is already way slower on Windows and this would bring it to a crawl especially if the item is near the end of the array. 

I'm also a little confused about the shell part on Windows. I know that the shell on windows is the desktop itself but I had a look at your Windows 7 rice page and under "Shell" it shows Blackbox/Litestep with Bash/Zsh together.

I'll keep working on this but the Windows portion of the script is already on feature parity with Linux/Mac OS X so It won't be a very high priority unless there's a larger demand for it. Pull requests are welcome if they meet the standards of the rest of the script. 

In the meantime your only option is to edit the array at the top of the script and add the Music player, Irc etc manually. If the script runs bug free for you then I'll close this issue as I think it's feature complete.

Thanks for your help!

**Comment by xDemonessx** [comment]
The shell section of nanami-tan is misleading, and I plan to change that alongside updating the cygwin area in general. It's not something I really like going into detail about on a windows related website, but it is unavoidable. 

http://win-bash.sourceforge.net/
https://babun.github.io/
http://zsh-nt.sourceforge.net/

some examples of urls and general updates that need to be pushed. 

I am in agreement that the features you have added for windows are more than sufficient and thank you for supporting it. I think it should be easy enough for someone to figure out how to modify the script to reflect accurate information should they choose to use it.

**Comment by dylanaraps** [comment]
Thanks for all the help!

**Comment by dylanaraps** [comment]
Neofetch now detects and shows some WMs/Shells by parsing `tasklist`

See these PRs: #373 #374 #375 

Support:

- wm: `bugn`, `Windawesome`, `blackbox`, `emerge`, `litestep`
- wm theme: `blackbox`

WM is shows like this:

```sh
WM: Bugn, Explorer
WM: BbLean (Blackbox), Explorer
WM: Litestep, Explorer
```

I know that showing Blackbox, Litestep and Emerge under WM is a little misleading and it's because I'm not sure entirely on how to differentiate between terminal shell and windows shell. 

Any ideas @xDemonessx?

**Comment by xDemonessx** [comment]
Sorry for a delayed reply, I've been out of town. The thing about displaying WMs such as bblean and bugn is that technically its still either dwm managing the windows, or bblean skin (plugin) styling them, or autohotkey moving them around. 

Detecting that these processes are running and then displaying them as you have shown is a great idea, and probably the best/most logical way of going about it. I doubt theres any way/reason to show "bbleanskin" is styling a window over an aero theme, or showing an autokey script (like bug.n) is being used to tile and move windows around... in the end most people will rely on aero/dwm and in truth thats what all windows users are probably sticking with when it comes to window management and themes.

My interpretation is this : blackbox, emerge, and litestep are shell replacements -  bug.n/ahk is the window managment, and aero + dwm are themes.

😕
