### ISSUE TITLE
Syntax Error on OS X

### ISSUE THREAD

**Issue by kleinmann** [dylanaraps/fetch#15]
I just tried `fetch` on OS X El Capitan (10.11.2) and received the following error:

```
~/bin/fetch: line 1095: syntax error near unexpected token `&'
~/bin/fetch: line 1095: `            ;;&'
```

I tried removing the ampersand, but that resulted in some kind of infinite loop. Can I do anything else to help pinpoint the problem?

**Comment by kleinmann** [comment]
Welp, seems like I overlooked the dependency on bash 4 :-) I'm closing this issue.

**Comment by dylanaraps** [comment]
If you're unwilling to install bash 4 the script also works with zsh. You just need to change the shebang at the top to "#!/bin/zsh".

**Comment by kleinmann** [comment]
That's good to know. I have installed bash 4 via homebrew now and it works als expected 😊 Thanks for your reply!

**Comment by dylanaraps** [comment]
No problem, thanks for using my script!
