### ISSUE TITLE
Blank Output on OSX

### ISSUE THREAD

**Issue by Goerofmuns** [dylanaraps/fetch#16]
Like literally nothing. 

It just gets stuck like this:

 ![this](http://i.imgur.com/tSOtZqr.jpg)

No output in regular terminal.app or iterm, when run from bash or fish. This is on OSX beta, but I doubt that would make a difference.

**Comment by dylanaraps** [comment]
Thanks for opening an issue!

* What's your bash version?

* Do you have all of the required dependencies?

* What happens if you launch the script with ```fetch --image off```

**Comment by Goerofmuns** [comment]
Bash is 4.3.42, from homebrew.

I have most of the optional and all of the required dependencies except for procps, for which I think there is no OSX version or equivalent.

Same output with --image off

Also just btw, pkgutil only shows software installed with the .pkg installer, so packages installed using homebrew, macports, and I think saveosx will not show up.

**Comment by dylanaraps** [comment]
There's an array on line 47. I want you to try removing lines from it in groups of 4 at a time. I'm pretty sure that one of the info functions is getting stuck. Once we figure out which function is freezing I can create a fix. 

> Also just btw, pkgutil only shows software installed with the .pkg installer, so packages installed using > homebrew, macports, and I think saveosx will not show up.

I see! I'll add support for homebrew, macports etc asap.

**Comment by Goerofmuns** [comment]
Kept removing them, and it kept freezing, even when I removed all of them. 

Also I just checked in an Ubuntu VM and the script runs, so it's not a corrupt or changed file. Hmm.

**Comment by dylanaraps** [comment]
Weird.

The script is freezing before the ```printinfo``` function is called which means it's either failing at OS detection or the tput related stuff. I've made a change to the OS detection so it exits and I've also added the extra package managers (homebrew, macports etc).

What output do you get now?

**Comment by Goerofmuns** [comment]
Ok I got the problem. bash -x is a wonderful thing apparently.

$image wasn't being set correctly for some reason, or it wasn't responding when it was set to "wall".
Hence, $img was not set, I think the OSX wallpaper detection might be broken in the script, so ImageMagicks identify tool was running with a blank argument. 

Hence it froze while waiting for input. I presume you don't have an OSX system to test on? I can poke around a bit to try and fix.

Also, iTerm2 has it's own image display system I think, ranger has w3m or iterm mode for it.

**Comment by dylanaraps** [comment]
Awesome, I didn't know about ```bash -x```!

I

Wall detection only works on Linux (with feh) and Windows so far. I don't have an OS X system to test it out on so it's difficult. I'll start working on support for it if you're willing to test.

**Comment by dylanaraps** [comment]
What do these commands output?

```sh
plutil -p ~/Library/Preferences/com.apple.desktop.plist
```

```sh
plutil -p ~/Library/Preferences/com.apple.desktop.plist | grep -F "ImageFilePath"
```

**Comment by Goerofmuns** [comment]
No Such file errors....

You may be able to do this with the osascript command, it's like a systemwide scripting language, I'll just have a look into it now.

**Comment by dylanaraps** [comment]
Added wallpaper detection on OS X to master.
