### ISSUE TITLE
Image disappears in Terminator

### ISSUE THREAD

**Issue by kelaun** [dylanaraps/fetch#18]
When executing the script, it shows my wallpaper for a fraction of a second and then it disappears.
![2016-01-18-150127_1280x1003_scrot](https://cloud.githubusercontent.com/assets/11407575/12393186/6e046278-bdf4-11e5-991f-9a4ba3bc90b2.png)
![2016-01-18-150130_1280x1003_scrot](https://cloud.githubusercontent.com/assets/11407575/12393187/6e12c408-bdf4-11e5-9285-93217a0ab91d.png)

**Comment by dylanaraps** [comment]
What terminal emulator are you using?

**Comment by kelaun** [comment]
Hi, 
Sorry for late response. I am using terminator.

**Comment by dylanaraps** [comment]
Alright, I've installed terminator and I can't seem to reproduce this.

- What font and size are you using?
- Can you upload your terminator config? `$HOME/.config/terminator/config`
- Does the problem still occur with a bitmap font?

**Comment by dylanaraps** [comment]
I think I can reproduce it now. Does running the script like this cause the image to always disappear?

```
fetch --clean
```

**Comment by kelaun** [comment]
Indeed running it with --clean always removes the image, but it is also removed without the --clean option.
I am using the Iosevka font on size 8
Here is my config:
[config.txt](https://github.com/dylanaraps/fetch/files/98070/config.txt)
Trying a bitmap font (Terminus) didn't help either.

**Comment by dylanaraps** [comment]
Alright, the image disappears for me when I focus terminator with the mouse and when the image is generated. (--clean forces the image to be regenerated).

Once the image is cached it displays fine.

Is this what you're seeing too?

**Comment by kelaun** [comment]
I tried launching fetch in a new window (without focusing it) but the image still disappears. I am never able to see it for more than a second.

**Comment by dylanaraps** [comment]
Do images in `w3m` or `ranger` work for you?

**Comment by kelaun** [comment]
Yes both work. You can see it in this screenshot:
![2016-01-20-221436_1366x768_scrot](https://cloud.githubusercontent.com/assets/11407575/12463340/45930f9e-bfc3-11e5-9427-6766b20fb8df.png)

**Comment by kelaun** [comment]
Just noticed that using scrot does some weird things with both ranger and w3m like seen on the screenshot. This can't be seen on screen though.

**Comment by dylanaraps** [comment]
Weird.

What happens if you add a `sleep 1` to line `1380` above the printf?

**Comment by kelaun** [comment]
It shows the image, removes it, then prints everything line by line. In the end it also removes the <username>@<hostname>

**Comment by dylanaraps** [comment]
Weird. 

What happens if you comment `printinfo` on line `1412`?

The text may be clearing the image.

**Comment by kelaun** [comment]
The image still disappears leaving me with an empty terminal.

**Comment by dylanaraps** [comment]
Keep printinfo commented and add the sleep on line `1380`. I want to see if it's a timing issue or if it's in the image gen function.

**Comment by kelaun** [comment]
I can see the image very briefly like before.

**Comment by dylanaraps** [comment]
What happens if you type this into the terminal directly?

```sh
clear; printf "%b%s\n" "0;1;0;0;200;200;;;;;$HOME/path/to/img.jpg\n4;\n3;" | /usr/lib/w3m/w3mimgdisplay
```
Change the path to a valid image before running it.

**Comment by dylanaraps** [comment]
iirc Terminator is vte based, do the images disappear in other vte based terminals? (xfce4-terminal or gnome-terminal or termite)

**Comment by dylanaraps** [comment]
Possibly related to: https://github.com/hut/ranger/issues/86

**Comment by dylanaraps** [comment]
Fixed!

The issue ended up being the `clear` on line `1380` being in the wrong place. We now clear the screen earlier and it fixes all flickering in vte based terminals. I've tested this in Terminator, Xfce4-terminal and Termite.

**Comment by CrashyBang** [comment]
Experiencing this on Termite (on ubuntu) but in a really weird way.

1) It was working `neofetch --image anon.jpg`
2) Restart terminal no longer working
3) Working with `neofetch --image anon.jpg --size 300px 305px`
4) Restart terminal now neither command is working...?

*Note:* Everytime it does not work I see the image flicker then disappear.

Is it some kind of caching rule, is there a way to get a more verbose output?

Cheers.

**Comment by dylanaraps** [comment]
Weird, I can't reproduce this at all.

- What neofetch version are you using?
- Does it still happen if you launch termite without a config?

**Comment by CrashyBang** [comment]
Hey @dylanaraps 

It's now working again there is 0 consistency here so I think it is something to do with my config, I will make a point of trying to drill down on it and post here again if I can isolate it with a little more detail.

Cheers.

**Comment by a-y-u-s-h** [comment]
I'm getting this error in `kitty` and `alacritty` terminals (both are GPU accelerated terminals). 

I'm not sure if it's related to `neofetch` or `w3m`. Image appears for a fraction of second and then disappears.
