### ISSUE TITLE
Exiting cleanly

### ISSUE THREAD

**Issue by shiftypenguin** [dylanaraps/fetch#20]
Heyo, I'm suggesting a few improvements for exiting the script cleanly. I haven't run the script on Linux, but on FreeBSD it doesn't exit well, and the prompt overlays the first line. Maybe it's my terminal (xfce term).

Anyway, it quits a lot more nicely if you add 

```
# Control-C clears screen
trap 'clear; exit;' 2
```
towards the top, and
```
# Pause at end, clear on keypress
read -n1 -s
clear
```
at the end.

I'm probably doing this wrong, because I have next to no github experience. sorry.

**Comment by dylanaraps** [comment]
I don't understand why we need these two blocks in the script.

The script starts and finishes too quickly for the trap part to work and I don't understand why we need to pause at the end and then clear the screen.

**Comment by shiftypenguin** [comment]
I suppose I should have explained why I made those changes. I'm smart.

The text acts weird. The prompt overlays the title, and each time you hit return our the shell outputs text, it slightly overlays the output of the script.

![2016-01-18-171127_1280x1024_scrot](https://cloud.githubusercontent.com/assets/4912515/12404149/0bce68de-be07-11e5-9345-6e032d8efa5d.png)
![2016-01-18-171203_1280x1024_scrot](https://cloud.githubusercontent.com/assets/4912515/12404151/0bd2f20a-be07-11e5-93cd-6e72a85dc89f.png)
![2016-01-18-171146_1280x1024_scrot](https://cloud.githubusercontent.com/assets/4912515/12404150/0bcf2e7c-be07-11e5-8455-76fcd48500c4.png)

**Comment by dylanaraps** [comment]
Does this command move the cursor to the bottom?

```
tput cup 100
```

I'm using ansi escape codes to move the cursor position and they may not work in *BSD for whatever reason, lets see if tput sets them correctly.

**Comment by shiftypenguin** [comment]
Huh. Cursor just goes to next line. Tested in TTY and xfce4-term

**Comment by dylanaraps** [comment]
Weird.

What about this line?:

```
tput cud 100
```

**Comment by dylanaraps** [comment]
I just booted up a vm and can reproduce this. 

None of the tput commands are working.

**Comment by shiftypenguin** [comment]
Same result.

**Comment by dylanaraps** [comment]
I'm pretty sure that *BSD uses termcap instead of terminfo and that the escape codes are different.

**Comment by dylanaraps** [comment]
I got it working.

```
tput DO 100
```

**Comment by dylanaraps** [comment]
Fixed.

Thanks for the issue!

**Comment by dylanaraps** [comment]
Ctrl+c now clears the screen, shows the cursor and exits the script.
