### ISSUE TITLE
GPU support.

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/fetch#21]
### An experimental version of GPU support is currently in master. 

Here's the status for GPU support:

- [X] Linux
- [X] Mac OS X
- [X] FreeBSD 
- [ ] OpenBSD
    - We could've used `pciutils` to get lspci functionality on OpenBSD but it turns out that it requires root.
- [ ] NetBSD
    - No clue on this one, I haven't been able to find a way to get gpu.
- [X] Windows

Adding support for OpenBSD and NetBSD is impossible at this point as I can't find a way to get the gpu name without needing root privileges.

#### All OS:

I'll need to see a screenshot of fetch.

#### Linux:
I'll need to see the output of this command:

```sh
lspci | grep  "VGA"
```

If the command above prints something vague instead of your gpu, your pci.ids files may be outdated. See this part of the readme on how to update them.

https://github.com/dylanaraps/fetch#getgpu-doesnt-show-my-exact-video-card-name

#### Mac OS X:
I'll need to see the output of this command:

```sh
system_profiler SPDisplaysDataType | awk -F': ' '/^\ *Chipset Model:/ {printf $2}'
```

#### FreeBSD:

I'll need to see the output of this command:

```sh
pciconf -lv 2>/dev/null | grep -B 4 "VGA"
```

#### Windows:

I'll need to see the output of this command:

```sh
wmic path Win32_VideoController get caption
```

**Comment by kelaun** [comment]
The output of 
> lspci | grep  "VGA"
for me is:
> 00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
> 01:00.0 VGA compatible controller: NVIDIA Corporation GK107M [GeForce GT 730M] (rev ff)

**Comment by dylanaraps** [comment]
What does the output look like when you enable gpu support?

**Comment by kelaun** [comment]
The output shows Nvidia GeForce GT 730M

**Comment by dylanaraps** [comment]
Awesome!

So it works fine for you?

**Comment by kelaun** [comment]
Yes, it does.

**Comment by dylanaraps** [comment]
I'm still stuck on `OpenBSD` and `NetBSD` gpu info and there doesn't seem to be 
interest from any Open/Net BSD users, so I'm closing this issue.

If someone does figure out how to get GPU info from `OpenBSD` or `NetBSD` open 
a new issue or send a PR.
