### ISSUE TITLE
Image disappears with i3

### ISSUE THREAD

**Issue by kelaun** [dylanaraps/fetch#23]
Continuing on issue #18, the problem also comes from the WM I am using (i3-gaps). When running
> fetch 

or
> fetch --clean

in the focused terminal, the image disappears.
Running
> terminator -e "fetch --clean;read"

open a new terminal where everything is correctly displayed. When focusing that terminal, everything is still displayed. When moving the focus to another window, the image disappears and never comes back.

**Comment by dylanaraps** [comment]
Let me install i3 and I'll see if I can reproduce this.

**Comment by dylanaraps** [comment]
The image disappearing on windows focus is an issue with w3m and terminator. It also happens with ranger and w3m itself.

**Comment by kelaun** [comment]
You're right, I never noticed it, but I get the same result in ranger now. I suppose you can close this issue as it is not related to your script :smile:

**Comment by dylanaraps** [comment]
Alright!

Thanks for the help testing!

**Comment by SajeOne** [comment]
I apologize for necroposting but is there any known workaround for this issue? I want to use this script but I have an attachment to i3-gaps and terminator and would rather not give them up. Thanks in advance! :)

**Comment by dylanaraps** [comment]
This is an issue with w3m-img and terminator, what window manager you're using doesn't matter. There's no known workaround for the issue either afaik, I'm currently writing a wiki page which explains the issues with w3m-img and known workarounds.

You can still use neofetch with terminator by using ascii mode. `neofetch --ascii` or change the config file to use ascii mode by default.

**Comment by dylanaraps** [comment]
Here's the new wiki page, this should hopefully clear up some confusion with how w3m-img works with neofetch.

https://github.com/dylanaraps/neofetch/wiki/w3m-img---Guide-[WIP]
