### ISSUE TITLE
[OS X] Multiple monitor resolutions

### ISSUE THREAD

**Issue by LostInInaka** [dylanaraps/fetch#25]
Not sure on non-OSX systems, but on OSX systems if you are running multiple monitors, the function will output the resolutions on to two lines, thus trying to print over a small part of the image display.

Therefore these output lines should probably be printed in to one line by slightly adjusting the following line under the `getresolution()` function
```sh
        "Mac OS X")
            resolution=$(system_profiler SPDisplaysDataType |\
                        awk '/Resolution:/ {printf $2"x"$4" "}')
        ;;
```

all i did was to change `print` to `printf` - this combines the output with a space on to one line only

**Comment by dylanaraps** [comment]
Thanks for opening the issue!

I've gone and changed all `print` to `printf` for consistency. 

The issue should be fixed now.
