### ISSUE TITLE
Disk Support

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/fetch#27]
### An experimental version of Disk support is currently in master. 

You can enable it by uncommenting this in the info function at the top of the script

```sh
info "Disk" disk
```

Here's the status for Disk support:

- [X] Linux
- [X] Mac OS X
- [X] FreeBSD 
- [ ] OpenBSD
    - Missing the launch flag needed to get total
- [ ] NetBSD
    - Missing the launch flag needed to get total
- [X] Windows

Adding support for OpenBSD and NetBSD is impossible at this point as I can't find a way to get the disk total since the launch flag I'm using for all other OS doesn't exist.

If you have an idea on how to get the total disk space of all disks on `OpenBSD` or `NetBSD`
then open a new issue or send a PR.

**Comment by mclado** [comment]
OS X - > works like charm, check!

**Comment by dylanaraps** [comment]
Thanks!
