### ISSUE TITLE
Add a config file

### ISSUE THREAD

**Issue by tudurom** [dylanaraps/fetch#29]
It would be a great idea to make fetch just some kind of framework used in conjunction with "theme" files. The theme files should describe the order of different components, align and other component options. There should be a default theme file for the current style and different components implemented in their own files.

I know bash at a basic level therefore I can't help :(

**Comment by dylanaraps** [comment]
The easiest way to achieve this would be to move all of the config options to a config file that you'd share with people. 

This way all someone has to do to get your "skin" is to copy your config and run the script.

**Comment by mclado** [comment]
Would be nice imo.

**Comment by dylanaraps** [comment]
I'm working on it!

**Comment by dylanaraps** [comment]
Config sourcing is done, all that's left is the creation of the config directory.

**Comment by dylanaraps** [comment]
**Config support is in a new branch called 'config', please test it out!**

There's a new file called `config` that contains the `printinfo` function and 
all of the script's options. You can easily share this file with people and keep it 
between versions.

Here's how it works:

1. We first look for `$config_file` and `--config path/to/config`
2. We then look for `$HOME/.config/fetch/config` and if it doesn't exist we
create the directory and copy the config file over.

Launch flags overwrite config options and config options overwrite options inside
the script. 

**bugs**: `--config path/to/config` creates `$HOME/.config/fetch`.

@mclado, @tudurom

**Comment by tudurom** [comment]
From what I see it works beautifully. Great job!

I'm leaving this issue up to you. Close it when you wish.

**Comment by dylanaraps** [comment]
It's in master now, I'll keep this open while I test it out with other OS.

**Comment by dylanaraps** [comment]
Here's what I've tested on:

- [X] Arch Linux
- [X] Windows

**Comment by dylanaraps** [comment]
Once someone can test this out on Mac OS X and confirm that it works, I'll close the issue.

**Comment by mclado** [comment]
When looking for Window Manager, script now runs X11 on my system, which is bad, because a lot of people don't have X11 installed on OS X anymore (it is not installed by default since mavericks I think). It also says  "_NET_WM_NAME:  not found", which is strange, because it was working fine before this config move.

Also I just can't get it working with this config file now, it never overrides fetch's defaults. Give me a little bit more time please so I can do some diagnosis.

**Comment by dylanaraps** [comment]
This is the commit that added xprop support to window manager detection: https://github.com/dylanaraps/fetch/commit/f0416ec78e76b39e1c4dc1d1839d09c75b3cd17e.

Xprop should only run if you've got it installed and it's weird that it's running on your system. I'm going to revert the commit until I can test it further.

**Comment by dylanaraps** [comment]
Where is the config file you're trying to edit stored?

**Comment by dylanaraps** [comment]
I just reverted the xprop stuff so those errors should be gone now.

**Comment by mclado** [comment]
Editing config file near fetch script and using `./fetch --config config` works flawlessly on OS X. Also the "x11 bug" is gone. :+1:

**Comment by dylanaraps** [comment]
Is the config file in `$HOME/.config/fetch/` not working for you? I'd rather you don't have to resort to using a flag to get it working.

**Comment by mclado** [comment]
Ok this is also working, didn't try that before.

**Comment by dylanaraps** [comment]
`$HOME/.config/fetch/config` is the default config file and it's created on script run. :)

**Comment by dylanaraps** [comment]
If it's working fine for you now, I'll close the issue!

**Comment by mclado** [comment]
Yeah!

**Comment by dylanaraps** [comment]
Thanks for testing!

**Comment by dylanaraps** [comment]
@mclado 

I just moved the config file to `config/config` in the repo, if you're still using `--config config` then you should update that to `--config config/config`.

This change was made to prevent us from sourcing any random file called `config` in the fallback to script directory part of the function.
