### ISSUE TITLE
[OS X] How much RAM is available & small things

### ISSUE THREAD

**Issue by mclado** [dylanaraps/fetch#32]
So let me explain you what I wanted to say yesterday on /r/.
OS X -> there is always max RAM consumption. Using your script, it clearly says only available RAM (which works nice on all kinds of unixes) - except here. A lot of that "used" ram can be used as free, because it is actually free. You actually have to check for RAM pressure here on OS X. I am bad in expressing those things in english; thats why I like you to view picture below and try to understand what I actually wanted to say, for example using screenfetch.

http://imgur.com/9DvgnpG

I also made red dot at shell because of version (which are you already going to implement) and green arrow because I don't know if this gap is supposed to be here or is it a bug. 

Also, what I would like to have here (disable by default, enabled via flagz):
- Terminal app: like Apple Terminal or iTerm.
- Batery status: like 50% or 100%
- IP address: like xxx.xxx.xxx.xxx

**Comment by dylanaraps** [comment]
I think I understand now. 

- I'll also include `compressed ram` in the OS X memory math.
- I'll add an option to print more kernel info (Will be disabled by default)
- I'll fix the huge gap below the script. (This is left over from the image mode as it's needed there)
- I'll add shell version support. (I have an idea on how to do it now)
- Battery status should be easy to add.
- I don't know if I want to add an IP address function, I'll think about it.

Detecting Terminal Emulator is one of the features I'd love to have but it's impossible without checking running processes and I don't want to resort to that. 

Thanks for the suggestions!

**Comment by dylanaraps** [comment]
It also seems like you have a random forward slash in your gpu output, I'll fix that too.

**Comment by mclado** [comment]
It's "Intel Iris /".

**Comment by dylanaraps** [comment]
What about this line?

```sh
system_profiler SPDisplaysDataType | awk -F': ' '/^\ *Chipset Model:/ {printf $2}' | awk '{ printf "%s ", $0 }'

```

**Comment by mclado** [comment]
This one is smooth, withtout "/". Nice!

**Comment by dylanaraps** [comment]
Awesome, I'll push it to master now.

**Comment by dylanaraps** [comment]
Also, see the 1.1 changelog for the new options:

https://github.com/dylanaraps/fetch/blob/master/1.1.md

**Comment by dylanaraps** [comment]
If the new features work fine for you, I'll close the issue.

**Comment by mclado** [comment]
Sure.

**Comment by dylanaraps** [comment]
Awesome, thanks!
