### ISSUE TITLE
Created ebuild for you

### ISSUE THREAD

**Issue by z1lt0id** [dylanaraps/fetch#33]
Hi Dylan,

Thought I'd make a Gentoo/Funtoo ebuild to add to your list of distros for an easy download.  I'll update it with every major release.

https://github.com/z1lt0id/fs0ciety/tree/master/x11-apps/fetch

**Comment by dylanaraps** [comment]
Awesome, thanks!

Are you able to install the ascii art to `/usr/share/fetch`? I've just pushed an update to master that checks that location before falling back to script location. 

Also, do I need to put any install instructions in the Readme for the ebuild?

**Comment by z1lt0id** [comment]
Sure I'll alter it now to go to usr/share/fetch - I wasn't sure what you 
wanted to do with that directory.  I'll respond shortly with what you 
can do regarding installing the ebuild in the readme.  Let me just make 
the commit and respond shortly.

Regards,
Dean

**Comment by z1lt0id** [comment]
Also are you wanting me to put it in /usr/share/fetch/ascii/distro or 
just /usr/share/fetch?

**Comment by dylanaraps** [comment]
`/usr/share/fetch/ascii/distro`

**Comment by z1lt0id** [comment]
So I get a whole bunch of errors with this new build now.  When doing the --ascii option (and sorry for the garbled output)
```
fsociety fetch # ine 1400: : No such file or directory
/usr-------------ine 1404: $ascii: ambiguous redirect
    OS: Funtoo Linux - baselayout 2.2.0
```

**Comment by dylanaraps** [comment]
It looks like the script can't find the ascii file and is then trying to continue with `ascii` mode instead of falling back to text mode.

Comment out `printinfo` on line `1937` and you should be able to see the error messages.

**Comment by dylanaraps** [comment]
How exactly did you launch the script?

This is how you launch it to display your distro's ascii:
```sh
fetch --image ascii

# or

fetch --ascii distro

```

**Comment by z1lt0id** [comment]
My bad - I was doing

```
fetch --ascii 
instead of
fetch --ascii distro
```

Maybe an error handler there is in order ;)

It's working now.  So I'll git push the ebuild.


As for how to install the ebuild.  I'll let you link to my repo if you like - unless you want to VM a gentoo box and create one.

Make you sure you have eix and layman installed (most gentoo/funtoo users do). If they don't they can by doing the following:

# add 3rd party repo
`layman -o https://gist.githubusercontent.com/z1lt0id/24d45b15800b98975260/raw/2fdf6645cdc3c1ca0b0af83a7bf8f86598e386ae/fs0ciety.xml -f -a fs0ciety`

# sync repos
`layman -S`

# to enable w3m and scrot support enable the appropriate flags
`echo "x11-apps/fetch" >> /etc/portage/package.use`

# install the package
`emerge -a x11-apps/fetch`

You can add w3m and scrot support by adding the flags to portage.use

**Comment by z1lt0id** [comment]
ps. ebuild is up to date and working

**Comment by dylanaraps** [comment]
Awesome, thanks for doing this!

I'll link to your repo, at least for the time being.

> Maybe an error handler there is in order ;)

Yup, will do!

**Comment by z1lt0id** [comment]
No problems :) Glad I could contribute in some way.

**Comment by dylanaraps** [comment]
I just updated the readme, we can close this now I assume.

https://github.com/dylanaraps/fetch#gentoo--funtoo

**Comment by z1lt0id** [comment]
Indeed :)

On 29 January 2016 12:16:47 pm AEDT, Dylan Araps <notifications@github.com> wrote:
>I just updated the readme, we can close this now I assume.
>
>https://github.com/dylanaraps/fetch#gentoo--funtoo
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/dylanaraps/fetch/issues/33#issuecomment-176509333

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dylanaraps** [comment]
Thanks again!

**Comment by dylanaraps** [comment]
@z1lt0id, fetch now supports config files so that you can share your configurations 
with others and keep your own changes between script versions. 

Here's how it works:

1. We look for a config file at `--config path/to/config` and `$config_file`
2. If it doesn't exist, we then look for `$HOME/.config/fetch/config`

If the config file isn't found anywhere we create `$HOME/.config/fetch` and copy the
config file from `/usr/share/fetch/config`. If `/usr/share/fetch/config` doesn't exist we
check the directory the script itself is located for a config file and copy that instead.

If the config isn't found anywhere the script runs normally.

The reason I'm telling you all this is that the ebuild is missing support for the config
files. All you have to do is install the file called `config` in the root of the git repo to
`/usr/share/fetch/config` and the script will do the rest! :)

**Comment by z1lt0id** [comment]
@dylanaraps fixing now.

**Comment by dylanaraps** [comment]
Awesome, thanks!

**Comment by z1lt0id** [comment]
@dylanaraps fixed.  In future if you need to get in contact regarding big updates email me at anonymous@fsociety.info :)

**Comment by dylanaraps** [comment]
Alright, will do!

Thanks!
