### ISSUE TITLE
Readme Screenshots

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/fetch#34]
I want to add some screenshots to the readme that aren't mine. Post some scrots below and I'll pick the best ones to put in the readme!

**Comment by mclado** [comment]
With default OSX distro image http://imgur.com/9EJc0Xs.

**Comment by dylanaraps** [comment]
Awesome!

Some cool things for you to try:

- Seeing as your color '0' matches the background, using `--block_range 1 7` will make the colors start at red instead of leaving a gap!

- Add `info linebreak` above `info title` in the printinfo array at the top to position the text similar to screenfetch.

**Comment by tudurom** [comment]
Here's mine: https://ipfs.pics/QmXSJZ3A7MmD8UrztHRQpUbqktCCgBF5Vdy4aUchQu7bVx

**Comment by dylanaraps** [comment]
Thanks!

**Comment by tudurom** [comment]
And with extra GNU magic:

![GNU magic](https://ipfs.pics/ipfs/QmPymvgHzPYr8YUxASEqvgDrLri9JcaHHqjDCqdQZK619S)

**Comment by dylanaraps** [comment]
`--gap` and `$gap` take a negative value btw, this means that you can push the text closer to the left of the terminal. :)

**Comment by z1lt0id** [comment]
And here is mwa

![fsociety](http://ibin.co/2VF11UcqRIUW)

**Comment by mclado** [comment]
Is that 25 TB o.O

**Comment by z1lt0id** [comment]
yup. i also have 2xgtx 970s.. but fetch doesn't display that ;)

**Comment by tudurom** [comment]
But why?

**Comment by dylanaraps** [comment]
Thanks for the screenshots guys!

@z1lt0id: 

- I just pushed an update to master that *should* fix the double space before the `@` sign in the cpu info.

- I'll see if I can count the gpus and add something like `...GTK 970 x 2`

**Comment by z1lt0id** [comment]
@tudurom It's a large collection of movies, tv, music and isos mostly.
@dylanaraps So many commits.. haha

**Comment by dylanaraps** [comment]
Thanks for the screenshots guys!

**Comment by dylanaraps** [comment]
@z1lt0id: What does this command output on your system?

```sh
lspci | grep -F "VGA"
```
I need the output to add support for counting the number of gpus. eg. `...GTK 970 x 2`

**Comment by z1lt0id** [comment]
```
01:00.0 VGA compatible controller: NVIDIA Corporation GM204 [GeForce GTX 970] (rev a1)
02:00.0 VGA compatible controller: NVIDIA Corporation GM204 [GeForce GTX 970] (rev a1)
```

**Comment by dylanaraps** [comment]
Thanks

**Comment by dylanaraps** [comment]
Try out master, I've added support for Linux.

**Comment by dylanaraps** [comment]
I just realised that it may not work due to the 01 and 02 on each line. I'll update it.

**Comment by dylanaraps** [comment]
It should be fixed now.

**Comment by Wyn10** [comment]
Am I too late?

![alt text](http://i.imgur.com/bl9esVl.png)

**Comment by dylanaraps** [comment]
You're a little late I'm afraid. I'll ask for some more screenshots at a later date to replace the current ones.

Stay tuned.

**Comment by mclado** [comment]
Hey there, it has been a while (quarter of the year exactly) since you updated readme with our scrots and I thought if you could do same thing again.

![neofetch_scrot_mclado](http://i.imgur.com/OkjOLSX.png)
