### ISSUE TITLE
For some reason fetch exits with exit code 1

### ISSUE THREAD

**Issue by tudurom** [dylanaraps/fetch#35]

**Comment by dylanaraps** [comment]
what happens if you comment out lines `363` - `366` and rerun the script?

**Comment by dylanaraps** [comment]
If it's still not working, change the shebang on line `1` to `#!/bin/bash -x` and rerun the script. Then upload the ouput to pastebin or equivalent and we'll be able to see what's causing this.

**Comment by tudurom** [comment]
It's not working with the first method. Falling to plan b.

**Comment by tudurom** [comment]
http://hastebin.com/yinumatilo.diff

**Comment by dylanaraps** [comment]
Try comment out lines `1962` to `1968`, I think the script's hanging at the `read` part of the if statment.

**Comment by tudurom** [comment]
Same

**Comment by dylanaraps** [comment]
Weird.

I just diffed your file and compared it to mine and there's nothing weird in yours.

**Comment by dylanaraps** [comment]
What's exactly happening? Does the script output anything or is it blank?

**Comment by dylanaraps** [comment]
Also, when did this start happening? We may be able to track this down to a specific commit.

**Comment by tudurom** [comment]
Well it behaves normally but it exits with 1.

**Comment by dylanaraps** [comment]
Ah, I see.

So there's a command failing somewhere in the script.

**Comment by dylanaraps** [comment]
I figured it out, It's the `printinfo` function.

**Comment by dylanaraps** [comment]
I'm working on a fix now.

**Comment by dylanaraps** [comment]
The error occurs because we're calling a function (getos) that doesn't exist on purpose, I'll add a dummy function and the error will be fixed.

**Comment by tudurom** [comment]
Nice. Now I can take a good screenshot to post it in the other issue.

**Comment by dylanaraps** [comment]
Fixed.

**Comment by tudurom** [comment]
It still returns 1. Reopen this.

**Comment by dylanaraps** [comment]
Sorry, I forgot to test the info functions that are disabled by default.

Are you using the `resolution` info function by any chance?

**Comment by tudurom** [comment]
I'm using defaults.

**Comment by dylanaraps** [comment]
I just pushed a commit to master, try it out now.

**Comment by tudurom** [comment]
Still 1...

**Comment by mclado** [comment]
As far as I know, return status 1 means general error, like dividing by zero or smth. Script itself does fine job; I actually echoed $? myself and found out 1 too. @tudurom can you post sc of your display after you run your script?
So script works just fine but with smth strange in it that bash can't process.
exit 0 at the end? :smiley:  :smiley:

**Comment by dylanaraps** [comment]
I can't reproduce this on my system, `echo $?` gives me a `0`!

Inside of the `printinfo` function, try commening out everything and replacing it with a single `echo`. Is the error status still a `1`?

**Comment by tudurom** [comment]
It turned into a 0 by magic!

**Comment by tudurom** [comment]
Now it's 1...

**Comment by tudurom** [comment]
Just discovered: in mksh it returns 0, but in zsh it returns 1.

**Comment by dylanaraps** [comment]
Ah, I'm using mksk. That explains why I can't reproduce this.

I'll swap over to zsh and test it out.

**Comment by mclado** [comment]
Replacing printinfo() with 'echo f' still returns 1 for me.

**Comment by tudurom** [comment]
But this is very strange, because the shebang tells the shell to run the script with bash. Running from bash interactively makes it return 1.

**Comment by dylanaraps** [comment]
What happens if you add `set -e` to the script above the `printinfo` function? `set -e` makes the script exit on the first error so it should indicate *where* it's failing.

**Comment by tudurom** [comment]
It looks the same.

**Comment by mclado** [comment]
Strange things happen, my indicator is gone and nothing is echo-ed.

**Comment by dylanaraps** [comment]
What happens if you comment this line?:

```sh
[ "$scrot" == "on" ] && takescrot
```
It's the last line in the script and commenting this fixes the exit code for me.

**Comment by mclado** [comment]
Just to be sure, I git pulled again, hard reset defaults, comment line number 1995 as you said and yes, return status is now 0!

**Comment by dylanaraps** [comment]
I'm pushing a fix to master now, I'll keep the issue open until @tudurom tests it out.

**Comment by dylanaraps** [comment]
It's in master now, please confirm that my fix works!

**Comment by tudurom** [comment]
Solved. Thanks for using your precious time for this.

**Comment by dylanaraps** [comment]
Thanks for reporting this, I wouldn't have known about it otherwise!
