### ISSUE TITLE
Bug in window manager recognition

### ISSUE THREAD

**Issue by tudurom** [dylanaraps/fetch#36]
This is a strange case here. I have a script called `wm` that executes bspwm for infinite times unless the exit code is 1. I use it for live reloading bspwm. Because of this, fetch says my window manager is called `Wm`.

**Comment by dylanaraps** [comment]
This is the unfortunate downside of us not checking for running processes to 
get the window manager. iirc screenfetch checks running processes and the
only reason we aren't doing the same is that it's *slow*. 

This is how fetch detects window manager:

1. We check using `wmctrl` if it's found
2. We check `$XDG_CURRENT_DESKTOP`
3. We then parse `$XINITRC`
4. Finally we parse `$HOME/.xinitrc`

You have a few options you can choose to correctly detect the window manager.

- Install `wmctrl`
- Set the variable `XDG_CURRENT_DESKTOP`
    - In your shellrc file (.zshrc, .bashrc, etc) add `export XDG_CURRENT_DESKTOP="bspwm"`

I'll have a look at other ways of detecting window manager as well but the detection 
steps above work for most people.

**Comment by tudurom** [comment]
Ended up installing wmctrl for /r/unixporn.

**Comment by dylanaraps** [comment]
I've added support for also using `xprop` to find the window manager and in my eyes there's enough methods of detecting the window manager now so I'm closing this issue.

Thanks for reporting this!
