### ISSUE TITLE
Add a Makefile

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/fetch#38]
The script has gone from being a single file to being a bunch of files which makes manual installation a little tricker for people. I propose that we add a `Makefile` to the script that installs the ascii art and default config to `/usr/share/fetch/` and installs the script itself to `${prefix}/bin`. 

I've already finished creating the Makefile and it works great, I just want to know what you guys think about it before pushing this to master.

```make
PREFIX        ?=  usr
RM            ?=  rm -f
INSTALL_DIR   ?=  install -m755 -d
INSTALL_PROG  ?=  install -m755 -D
INSTALL_FILE  ?=  install -m644 -D

all:
	@echo Run \'make install\' to install Fetch

install:
	$(INSTALL_DIR) $(DESTDIR)/$(PREFIX)/bin
	$(INSTALL_DIR) $(DESTDIR)/usr/share/fetch/ascii/distro
	$(INSTALL_PROG) fetch $(DESTDIR)/$(PREFIX)/bin/fetch
	$(INSTALL_PROG) config $(DESTDIR)/usr/share/fetch/config
	$(INSTALL_PROG) ascii/distro/* $(DESTDIR)/usr/share/fetch/ascii/distro

uninstall:
	$(RM) $(DESTDIR)/$(PREFIX)/bin/fetch
```

**Comment by z1lt0id** [comment]
Fine by me, makes my ebuild much simpler than managing all those files manually.

**Comment by dylanaraps** [comment]
Awesome!

Should `make uninstall` also remove ascii and configs? Or should we leave it how it is above?

**Comment by z1lt0id** [comment]
I guess that would be good for people who manually use the make install process, but for the ebuild that isn't required.

**Comment by dylanaraps** [comment]
Makefile is in master.
