### ISSUE TITLE
Default image thumbnail directory.

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/fetch#39]
The script currently defaults to storing the image thumbnails in `$HOME/.fetchimages`. Is this an ok place to be storing the thumbnails by default or should we store them somewhere else?

**Comment by tudurom** [comment]
You may store them in `.local`.

**Comment by dylanaraps** [comment]
Good idea, I did some googling and also found `.thumbnails` which is where file managers etc store generated thumbnails. This folder serves as an image cache and seems to be ideal for what we want to use it for.

What do you think?

**Comment by tudurom** [comment]
I think `.local` is more standard, so it's better.

**Comment by dylanaraps** [comment]
There's also `.cache/thumbnails` which is where w3m stores it's generated thumbnails.

**Comment by dylanaraps** [comment]
`.cache` is in the [XDG Directory Spec](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html)

**Comment by tudurom** [comment]
I knew there was a `.cache` somewhere... Can I do it, I mean submit the commit?

**Comment by dylanaraps** [comment]
Sure, just change `$imgtempdir` to `$HOME/.cache/thumbnails/fetch` inside the script and inside of `config/config`!

**Comment by tudurom** [comment]
You can close the issue.

**Comment by dylanaraps** [comment]
Thanks for the help!
