### ISSUE TITLE
My wallpaper doesn't appear anymore

### ISSUE THREAD

**Issue by tudurom** [dylanaraps/fetch#40]
For some reason fetch runs only in screenfetch mode. The issue persists when I run fetch with `--image wall`.

**Comment by dylanaraps** [comment]
I'll try and find the commit that broke this for you.

**Comment by dylanaraps** [comment]
Does the image display in this version:
https://github.com/dylanaraps/fetch/tree/6c20e2c5d5450be45610362703d41b56aae537b6

This is one commit behind what I *think* is breaking image mode for you.

**Comment by tudurom** [comment]
Still ascii.

**Comment by dylanaraps** [comment]
We've got to find the last working version, so how about this one?

https://github.com/dylanaraps/fetch/commit/3cfd88f5742f0056f3ad302beb4df0d9670df060

**Comment by tudurom** [comment]
It doesn't work either with this ridiculously old commit (2d6e92440f265f25a0da33f12ce0f6779a25898f), so it is by my side, but I don't know why.

**Comment by dylanaraps** [comment]
Try this one: 
https://github.com/dylanaraps/fetch/tree/d683593c2d28e696121af49712e0222139a62774

This is one commit before I added a function to automatically find w3m-img. This function may be failing on your system. (When the function fails it fallback to ascii mode).

**Comment by tudurom** [comment]
I uninstalled imagemagick by mistake, my bad.

**Comment by dylanaraps** [comment]
Ohhh

That makes sense!

**Comment by dylanaraps** [comment]
No problem :)
