### ISSUE TITLE
Manjaro: Packages are "Unknown"

### ISSUE THREAD

**Issue by LavaEagle2003** [dylanaraps/fetch#45]

**Comment by dylanaraps** [comment]
Add `set -x` to the second line of the script and then upload the output to pastebin.

**Comment by dylanaraps** [comment]
Ping @LavaEagle2003

**Comment by tudurom** [comment]
I installed Manjaro in a VM and the package count works, but there's another problem with the ascii logo...

![scrot](https://ipfs.pics/ipfs/QmQDHfChZe8zCsRrkqime5EmKDKCsEazqs188mS4xzPqhf)

**Comment by dylanaraps** [comment]
Let me boot up my Manjro vm.

**Comment by dylanaraps** [comment]
Also, you can test this on other distros using `--ascii_distro manjaro`.

**Comment by dylanaraps** [comment]
@tudurom, I can't reproduce this on a fresh manjaro install. 

Try launching fetch like this `fetch --ascii --ascii_distro manjaro` on your main system
to see if it also affects it.

**Comment by tudurom** [comment]
On my main system it works just right, but on Manjaro on xfce4-terminal and on urxvt it is glitched.

**Comment by tudurom** [comment]
Just updated the whole thing. Doesn't work.

**Comment by dylanaraps** [comment]
Is your locale the same in your main system and in the virtual machine?

**Comment by tudurom** [comment]
No. I chose Romanian by mistake in the vm. I will see if it works in xterm because xterm doesn't have unicode support.

**Comment by dylanaraps** [comment]
I'm pretty sure that it's the locale then.

**Comment by tudurom** [comment]
But why?

**Comment by LavaEagle2003** [comment]
Sorry, I was busy for a few days. But the issue is solved in the latest edition.

**Comment by tudurom** [comment]
@dylanaraps After setting the locale to en_US it looks normal now but that's strange.

**Comment by dylanaraps** [comment]
Will do.
