### ISSUE TITLE
Split some functionality into their own files

### ISSUE THREAD

**Issue by tudurom** [dylanaraps/fetch#48]
Let's say I want to write in my panel script a function to display the time when the battery will be fully charged. Let's say fetch can display that. Instead of looking through fetch's huge script just for a little function, if the function would have its own script, then I could call the script directly. I say there should be a number of little scripts for hostname, remaining battery, RAM etc. that should work on Linux, Mac, BSD and Windows. Fetch will call these functions from their files, while I can use one of the files in my bar script.

Solution: extract fetch's functionality in small scripts that should only print to stdout the desired information. For example, the `fetch_battery` script should only print "92".

Sound good enough? If yes, I will do it and I will self-assign this issue.

**Comment by dylanaraps** [comment]
I really don't want to split fetch into any more files unless we have to. Even though the script has multiple files it still works on its own. If we move the functions away from the script then nobody
will be able to just drop it into their path, they'll have to install it entirely.

I've come up with a better solution, it's almost done in my local branch.

I've created a new helper function called `stdout` which prints the function output to stdout without
any escape codes, newlines etc. This is what the printinfo function will look like:

```sh
printinfo () {
    # Print the info in the "Title: output" format.
    stdout "OS: distro"
    stdout "Kernel: kernel"
    # Print the memory without a title.
    stdout "memory"
}
```

You'll then launch the script like this:

```sh
fetch --image off
```

Here's a screenshot of what it looks like when used in a lemombar script:
![bar](http://i.imgur.com/aswRsH2.png)
**NOTE:** Click the image for a larger version
**NOTE:** I've added the ' | ' myself with a printf

What do you think?

**Comment by tudurom** [comment]
It looks nice. I will test it this afternoon (5 hours since now).

**Comment by dylanaraps** [comment]
Awesome!

**Comment by dylanaraps** [comment]
Another option is to add a flag `--stdout` or `--bar` which will convert the existing `info "CPU" cpu` lines to the `stdout` lines. This way the user can use the same `printinfo` function for lemonbar and fetch.

**Comment by dylanaraps** [comment]
I figured out how to add `--stdout` in just a few lines and it works with existing `info "CPU" cpu` syntax!

**Comment by dylanaraps** [comment]
I've pushed a better (imo) solution to a new branch called `stdout2`. This version adds a new flag called `--stdout` which prints the **existing** printinfo function in a lemonbar compatible format. This new version is much smaller and allows you to use the same config without any modification.

This version also adds 3 new launch flags and config options:

- `stdout_title`: Toggle the display of `title@hostname` in the output. 
- `stdout_seperator`: Takes a string which it adds to the end of each bit of info as a seperator. 
    - eg. `--stdout_seperator "  |  " `
- `stdout_subtitles`: Toggle the display of each info's subtitle in the output.

Please test it out!

**Comment by tudurom** [comment]
Let's say I have a bar script and I want to display the CPU in the left and the GPU in the right. I need two different config files to do that. Correct me if I'm wrong.

**Comment by tudurom** [comment]
I think the `stdout` functions should be there.

**Comment by dylanaraps** [comment]
The problem with the `stdout` function is that it requires users to have two configs if they want to use fetch and stdout.

**Comment by dylanaraps** [comment]
I have an idea though.

**Comment by tudurom** [comment]
Why not an `enable` flag?

**Comment by dylanaraps** [comment]
A new flag which **only** runs the functions that the flag is given, so:

```sh
fetch --stdout --function cpu gpu etc
```

**Comment by dylanaraps** [comment]
That's what I was typing :)

**Comment by tudurom** [comment]
Why not simplify?

```bash
fetch --stdout cpu gpu etc
```

**Comment by dylanaraps** [comment]
Having a general flag allows it to work with fetch as well.

**Comment by tudurom** [comment]
I don't understand.

**Comment by dylanaraps** [comment]
```sh
fetch --enable cpu gpu memory
```

This will only display cpu, gpu and memory in the regular fetch output.

**Comment by tudurom** [comment]
Ah ok.

**Comment by dylanaraps** [comment]
The only issue with `--enable` is setting the subtitle, in the `info` functions the user has to specify a title but with this flag it'll complicate things.

I think I'll just add `--stdout cpu gpu memory etc` and make it print the info without a subtitle.

What do you think?

**Comment by tudurom** [comment]
Leave it as `--stdout etc` temporary.

**Comment by dylanaraps** [comment]
I can add `--stdout etc` but you won't be able to have subtitles infront of the info.

**Comment by tudurom** [comment]
That was the whole purpose... just the info.

**Comment by dylanaraps** [comment]
Alright, I've pushed an update to the `stdout2` and --stdout cpu etc` now work.

**Comment by dylanaraps** [comment]
I'm also going to remove the new flags as they're useless with this new behaviour.

**Comment by tudurom** [comment]
It works beautifully, can you put it in master?

**Comment by dylanaraps** [comment]
I just need to write some docs about it and update the readme.

**Comment by tudurom** [comment]
BTW showing battery info doesn't work.

**Comment by dylanaraps** [comment]
Also setting `--stdout_seperator` doesn't work when `--stdout` has args, so I'm going to fix this too before I push to master.

**Comment by dylanaraps** [comment]
Battery is the only function that makes use of `prin`, I'll have a look.

**Comment by dylanaraps** [comment]
It's because `prin` prints a newline, I'll fix this.

**Comment by dylanaraps** [comment]
I just pushed a fix for the battery info, try it out!

**Comment by tudurom** [comment]
It prints all the other info and then the battery. Not good.

**Comment by dylanaraps** [comment]
Oh, what do you mean?

**Comment by dylanaraps** [comment]
I've figured it out.

**Comment by dylanaraps** [comment]
I just pushed another fix, try it out.

**Comment by tudurom** [comment]
Running `fetch --stdout battery` yields

```
off60\033[0m8: 799%    OS: Arch Linux x86_64    Kernel: 4.3.5-1-ck    Uptime: up 1 hour, 53 minutes    Packages: 839    Shell: /bin/mksh    Window Manager: Bspwm    GTK Theme: Arc-Darker [GTK2/3]    Icons: UltraFlatIcons [GTK2/3]    CPU: Intel Core i5-3210M @ 3.1GHz    GPU: Nvidia NVS 5400M    Memory: 726MB / 7737MB    Birthday: Fri 27 Nov 2015 12:39 AM    Battery*: 99%    
```

**Comment by dylanaraps** [comment]
What's the first battery in your system called?

**Comment by tudurom** [comment]
0

**Comment by dylanaraps** [comment]
How many batteries do you have in your system?

**Comment by tudurom** [comment]
1

**Comment by dylanaraps** [comment]
I just pushed another fix, try it out.

**Comment by tudurom** [comment]
```
off6[0m8: 799%    
```

799?

**Comment by tudurom** [comment]
Btw don't forget to test in normal mode, there are bugs in here.

**Comment by dylanaraps** [comment]
Progress!

There are some escape codes which need to be removed.

**Comment by dylanaraps** [comment]
What does normal mode look like?

**Comment by dylanaraps** [comment]
I can't test the battery stuff myself.

**Comment by tudurom** [comment]
![pic](https://ipfs.pics/QmQz1aPSB5xXqFuECPguEYbU38Mf2JTmAyxieesDR86UM5)

**Comment by dylanaraps** [comment]
Pic is not found.

Also I just pushed another commit to `stdout2`, try it out.

**Comment by tudurom** [comment]
Not found? Refresh.

**Comment by dylanaraps** [comment]
Image is still not found for me

**Comment by tudurom** [comment]
Now it works perfectly, but in normal it no longer shows `Battery0: 99%`. It shows `Battery`, without the 0.

**Comment by dylanaraps** [comment]
The reason the battery output wasn't working properly in stdout mode is because `$battery` wasn't being set and we were directly printing the info instead. The fix is to use the subtitle from `printinfo` if there's only a single battery detected.

So in short, the battery info will now print the subtitle without a number if there's only a single battery detected.

**Comment by tudurom** [comment]
Ah ok. We should keep the issue open until you replace `--stdout` with `--enable`.

**Comment by tudurom** [comment]
Thanks!

**Comment by dylanaraps** [comment]
I want to add `--enable` but the user won't be able to set the subtitle unless the flags look like this:

```sh
fetch --enable "CPU: cpu" "Memory: memory"
```

How does that look?

**Comment by tudurom** [comment]
As a temp fix, it looks good.

**Comment by dylanaraps** [comment]
I don't think we can get any cleaner than that tbh,

**Comment by tudurom** [comment]
Then push it.

**Comment by dylanaraps** [comment]
I don't think I can add `--enable` without some work, I'm going to just leave it at `--stdout cpu etc` for now. I'll push to master once I've done some cleanup and written some docs about it. 

It's 2 am here so I'm going to bed and I'll finish this up tomorrow.

Thanks for the help!

**Comment by tudurom** [comment]
Thank you too and good night!

**Comment by dylanaraps** [comment]
Merged, thanks again!

Note: `--stdout_seperator` now works with `--stdout cpu gpu etc`

**Comment by tudurom** [comment]
See #50

**Comment by dylanaraps** [comment]
Thanks

**Comment by tudurom** [comment]
You're lucky because in my native language the word for "separator" is
exactly "separator" and I thought something was not right. You're welcome!

**Comment by dylanaraps** [comment]
What's your native language?

**Comment by tudurom** [comment]
Romanian. A very hard language.

**Comment by dylanaraps** [comment]
Mine's English but I also speak Greek. :)

**Comment by tudurom** [comment]
That was.... unexpected. Let's end this discussion because it floods the
watchers' mailboxes.
