### ISSUE TITLE
Installation doesn't work on OS X El Capitan

### ISSUE THREAD

**Issue by cpressland** [dylanaraps/fetch#53]
After cloning the repo and running "make install" a "Operation not permitted" message is shown:

```
cpressland@cpressland-mbp ~/git/fetch (master)$ make install
install -m755 -d /usr/bin
install: chmod 755 /usr/bin: Operation not permitted
install -m755 -d /usr/share/fetch/ascii/distro
install: mkdir /usr/share/fetch: Operation not permitted
make: *** [install] Error 71
```

I'm fairly sure this is as a result of the 'rootless' functionality of El Capitan, documented [here](http://apple.stackexchange.com/questions/193368/what-is-the-rootless-feature-in-el-capitan-really) and [here](https://support.apple.com/en-gb/HT204899)

**Comment by dylanaraps** [comment]
The stackexchange link says that you can still edit `/usr/local` as root on El Captain. 

Try installing it like this:

```sh
PREFIX=/usr/local make install
```

If the above doesn't work then we'll need to look into creating a `homebrew` package for fetch.

**Comment by cpressland** [comment]
No luck, throws the following instead:

```
cpressland@cpressland-mbp ~/git/fetch (master)$ PREFIX=/usr/local make install
install -m755 -d //usr/local/bin
install -m755 -d /usr/share/fetch/ascii/distro
install: mkdir /usr/share/fetch: Operation not permitted
make: *** [install] Error 71
```

**Comment by dylanaraps** [comment]
It looks like the script itself installed to `/usr/local/bin` just fine. The problem is the ascii art and the default config which are installed to `/usr/share/fetch`. 

I'm going to modify the makefile to also install to `$PREFIX`, this will fix the issue.

**Comment by cpressland** [comment]
Awesome! Thanks for the update. Let me know when you've done a commit and I'll test again.

**Comment by dylanaraps** [comment]
I just pushed to master, try this command again:

```sh
PREFIX=/usr/local make install
```

**Comment by cpressland** [comment]
Line 4 & 5 of Makefile should be lowercase "d" right? 

```
  1 PREFIX        ?=  /usr
  2 RM            ?=  rm -f
  3 INSTALL_DIR   ?=  install -m755 -d
  4 INSTALL_PROG  ?=  install -m755 -D
  5 INSTALL_FILE  ?=  install -m644 -D
```

Error: `install: illegal option -- D`

**Comment by dylanaraps** [comment]
You're right, I'll lowercase the d's.

**Comment by dylanaraps** [comment]
Fixed. 

Try installing using the command above now.

**Comment by cpressland** [comment]
Awesome, confirmed as installing correctly. Closing issue.

**Comment by dylanaraps** [comment]
I'll make a note in the readme about the prefix for El Captain users.
