### ISSUE TITLE
Operating system support

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/fetch#55]
This issue will serve as a list of Operating systems and distros that fetch has been
confirmed to work on. 

Fetch has been confirmed to work on these Operating systems:

**Linux**

- [X] Arch based distros
- [X] Ubuntu based distros
- [X] Fedora
- [X] Gentoo / Funtoo
- [X] openSUSE
- [X] Puppy Linux (Quirky Werewolf)
- [X] Mageia Linux
- [X] Raspbian
- [X] PCLinuxOS
- [X] Zorin OS
- [X] Tails
- [X] BLAG
- [X] Void Linux
- [X] Solus
- [X] NixOS
- [X] Chakra
- [X] OpenMandriva
- [X] LMDE
- [X] gNewSense
- [X] KaOS
- [X] Sabayon
- [X] Frugalware

The support is there for more distros they just haven't been
tested or confirmed to be working by anyone.

**Windows (Cygwin)**
We're missing Resolution support for all windows versions.

**Mac OS X**
Everything should work.

**BSD**
We're missing Disk and GPU support for all BSD flavours.

- [X] FreeBSD
- [X] OpenBSD
  - We're missing Battery support. 
- [X] NetBSD
    - We're missing Battery support. 

For those wanting to help, here are the remaining distros that need 
support/testing before we're at support parity with screenfetch.

- Slackware
- Scientific Linux
- Chapeau
- deepin

**Comment by dylanaraps** [comment]
Tomorrow I'll be testing:

- Puppy Linux
- Kali Linux

**Comment by tudurom** [comment]
I'm an ex openSuse user and I know little bits of information. If you need help I'm here.

**Comment by dylanaraps** [comment]
Thanks!

**Comment by dylanaraps** [comment]
Puppy Linux:

- Packages shows "Unknown"
- Uptime has a weird output
- Window manager detection fallsback to parsing xinitrc and fails
because the xinitrc doesn't exec a single time.

![puppy](http://i.imgur.com/3KhhXli.png)

**Comment by dylanaraps** [comment]
Kali Linux:

- Packages shows "Unknown"

**Comment by dylanaraps** [comment]
OpenSuse:

**Comment by tudurom** [comment]
[Maybe this helps for openSuse?](https://github.com/KittyKatt/screenFetch/blob/master/screenfetch-dev#L1057)

There may be other surprizes: many programs are stored in sbin. OpenSuse is very idiot-proof.

**Comment by dylanaraps** [comment]
Fixed the GPU issue.

**Comment by tudurom** [comment]
[For resolution detection on Windows](https://github.com/KittyKatt/screenFetch/blob/master/screenfetch-dev#L1310).

Screenfetch has all the answers you need.

**Comment by dylanaraps** [comment]
I've already looked there and those commands didn't work on the 3 Windows PCs I tried them on.

**Comment by dylanaraps** [comment]
Added support for `Mageia Linux`.

**Comment by dylanaraps** [comment]
Added support for `PCLinuxOS`

**Comment by tudurom** [comment]
You gave me an idea: I will make a sepparate project: a unified way to
query different package managers. It will act like a bridge for various
other programs. Thanks!

**Comment by dylanaraps** [comment]
Awesome!

Send me the link when it's on github and I'll try and help out. :)

**Comment by dylanaraps** [comment]
Added support for `Zorin OS`.

**Comment by dylanaraps** [comment]
Added support for `BLAG`

**Comment by dylanaraps** [comment]
Confirmed support for `Void Linux`.

**Comment by dylanaraps** [comment]
Added support for Trisquel.

**Comment by dylanaraps** [comment]
Added support for `Solus`

**Comment by dylanaraps** [comment]
Added support for `Peppermint Linux`.

**Comment by tudurom** [comment]
Shouldn't be simpler for rpm or deb based distro to check if rpm or deb is
available and the get the package count? It would be simpler. Same for
`emerge` and `pkginfo`.

**Comment by dylanaraps** [comment]
I don't quite understand your comment (sorry), can you clarify?

**Comment by dylanaraps** [comment]
Added support for `NixOS`.

**Comment by dylanaraps** [comment]
Added support for `Chakra`.

**Comment by tudurom** [comment]
This is how fetch gathers the package count on distros using `dpkg` for package management:

```bash
"Ubuntu"* | *"Mint"* | "CrunchBang"* | "Debian"* | "Kali"* | "Deepin Linux"* |\
        "elementary"* | "Raspbian"* | "Zorin"* | "Tails"*)
            packages="$(dpkg --get-selections | grep -cv deinstall$)"
        ;;
```

It can be simplified by checking if the `dpkg` binary is available and then getting the package count. This way it will work for an infinite number of `dpkg` based distro. Same can be accomplished for other distros by checking for their package manager: `pacman` on Arch, Parabola, Manjaro and other, `pkginfo` on Crux, `emerge` on Gentoo and Funtoo and the others...

**Comment by dylanaraps** [comment]
Great idea!

This would make it easier to add new distros, all we'd need to do is add
ascii art. I've got about `30` virtual machines of various linux distros so 
I'll create a new branch and test it out! :)

Btw, we're `10` linux distros away from supporting all distros `screenfetch` 
supports. (I'm excluding discontinued distros.) Once I add support for the 
last 10 distros I'll look through screenfetch's issue tracker at people's distro 
requests and add those too.

**Comment by dylanaraps** [comment]
Added support for `OpenMandriva`.

**Comment by dylanaraps** [comment]
Added support for `KaOS`.

**Comment by dylanaraps** [comment]
For those wanting to help add support for other distros, here are the
remaining distros that need support/testing before we're at support
parity with screenfetch.

- Sabayon
- Slackware
- Frugalware
- Scientific Linux
- Chapeau
- deepin

**Comment by dylanaraps** [comment]
Added support for `LMDE` and `gNewSense`.

**Comment by dylanaraps** [comment]
Added support for `Sabayon`.

**Comment by dylanaraps** [comment]
Added support for `Frugalware`.

**Comment by tudurom** [comment]
Why not switch to package manager-based checking?

**Comment by dylanaraps** [comment]
See #71

**Comment by tudurom** [comment]
I know about #71. Why not merge that?

**Comment by dylanaraps** [comment]
I want your opinion about it before I merge it.

**Comment by tudurom** [comment]
You can close the issue and create a new one for supporting new package managers.

**Comment by aprilahijriyan** [comment]
Hi @dylanaraps, I have tested the neofetch on Deepin OS but it doesn't work for images.
