### ISSUE TITLE
Text padding is wrong on locale other than English

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/fetch#57]
Example:

![scrot](https://camo.githubusercontent.com/3753aeffa4cd429371e82f0be49cbf53949640a4/68747470733a2f2f697066732e706963732f697066732f516d5144486643685a65387a437352726b71696d6535456d4b444b437345617a71733138386d5334787a50716866)

**Comment by dylanaraps** [comment]
@tudurom: I can't seem to reproduce this, can you send me the exact locale string? 

It should look something like this: `en_US.UTF8`

**Comment by tudurom** [comment]
I think it is `ro_RO.UTF-8`.

**Comment by dylanaraps** [comment]
I still can't reproduce this!

@tudurom, does this happen with all ascii logos or only Manjaro's?

**Comment by dylanaraps** [comment]
Also, what's the output of this command on the manjaro system?

```sh
locale
```

**Comment by tudurom** [comment]
I, umm, deleted the VM.

**Comment by tudurom** [comment]
It happens with all of them.

**Comment by dylanaraps** [comment]
Are you able to reproduce this on your main system? If so, does it happen with screenfetch also?

**Comment by dylanaraps** [comment]
I just pushed a possible fix to master, just run the script and let me know if the problem persists.

**Comment by tudurom** [comment]
It's 3am here, so I will go to bed. See you in 8-9 hours!

**Comment by dylanaraps** [comment]
Yup, no problem!

**Comment by tudurom** [comment]
It works, but only after I installed the English locale. Should this be considered a temp solution?

**Comment by dylanaraps** [comment]
I have an idea on how to fix it completely and it won't require installing the English locale. I'll push it to a branch for you to test.

**Comment by dylanaraps** [comment]
Try the branch `locale_fix`.

**Comment by tudurom** [comment]
Yes, it works! Close it.

**Comment by dylanaraps** [comment]
Awesome!

Thanks for testing.
