### ISSUE TITLE
Fetch is the 5th trending repo on the "Shell" category

### ISSUE THREAD

**Issue by tudurom** [dylanaraps/fetch#58]
We need to put it on the first place!

Seriously, great job Dylan and contributors!

**Comment by dylanaraps** [comment]
Awesome! :)

**Comment by tudurom** [comment]
[Proof](http://github.com/trending/bash) (for the lazy)

**Comment by mclado** [comment]
Great job!

**Comment by dylanaraps** [comment]
Closing this as we're now way up the list.
