### ISSUE TITLE
IP Address support

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/fetch#59]
I'm working on implementing support for showing your Local IP
address and your Public IP address in fetch. 

I'm working on it inside a new branch called `ip`. Windows and
Linux support is done for the Local IP function.

For those wanting to test, checkout the `ip` branch and add these
lines to your printinfo function in your config:

```sh
info "Local IP" localip
info "Public IP" publicip
```

**NOTE**: The public IP features requires an internet connection
as we ping a website for the public IP.

**Comment by dylanaraps** [comment]
@mclado

What do these commands output?

```sh
# This should be wireless
ipconfig getifaddr en1

# This should be ethernet
ipconfig getifaddr en0
```

**Comment by mclado** [comment]
First one does nothig, the second one and the third one says `192.168.0.102`, looks like my internal address in local NAT.

**Comment by mclado** [comment]
Also if you need to know, I am connected via wifi.

**Comment by dylanaraps** [comment]
Awesome, I'll add something like this:

```sh
localip="$(ipconfig getifaddr en0)"

[ -z "$localip" ] && localip="$(ipconfig getifaddr en0)"
```

**Comment by dylanaraps** [comment]
I just pushed to the new `ip` branch, add `info "Local IP" localip` to the printinfo function in your config and tell me whether or not the ip stuff works! :)

**Comment by aaronmehar** [comment]
For public IP, you can do 
```
publicip=$(curl -s icanhazip.com)
```

Excuse formatting, in mobile. I can look later and maybe send a PR.

**Comment by dylanaraps** [comment]
I've actually got the public ip part done in my local branch. :)

**Comment by dylanaraps** [comment]
I've added support for all operating systems, I'm opening a pull request before I merge this to master.

**Comment by dylanaraps** [comment]
Move discussion to: **#60**
