### ISSUE TITLE
Add Raspberry PI support on Raspbian!

### ISSUE THREAD

**Issue by mclado** [dylanaraps/fetch#61]
Basics from making another `$os` to `uname` to fixing all current commands to work on it!

Also time to create new ascii image to display it there!

And so on...

**Comment by mclado** [comment]
Don't know how to assign this task to users. :laughing:

**Comment by dylanaraps** [comment]
What's the output of `uname`?

**Comment by mclado** [comment]
Hey sorry, something came in today so I had no time to boot thing up & install newest Raspbian. Gonna do it tommorow. We have 8 hours time delay anyway.

Was also thinking about ascii image, came up with great idea, I just have to realize it. :laughing:

**Comment by dylanaraps** [comment]
No problem!

**Comment by mclado** [comment]
So I just installed latest OS from https://www.raspberrypi.org/downloads/raspbian/ called Raspbian Jessie. Booted up without internet connection with default settings and uname says Linux for me. Mkey then, let me copy your script. Guess what. 

[Imgur](http://i.imgur.com/q1sPBdM.jpg)

Works like it should (default config). Now we need to fix packages.

**Comment by mclado** [comment]
Scrot function also works but without internet I had to take picture with phone.

**Comment by dylanaraps** [comment]
Awesome!

> Now we need to fix packages.

Fixed.

**Comment by dylanaraps** [comment]
Ascii art is also done.

Once you can confirm that this works on your PI, we can close this issue.

**Comment by dylanaraps** [comment]
Ping @mclado.

**Comment by dylanaraps** [comment]
Closing this as it should work just fine.

**Comment by vallovic** [comment]
Following installation instructions for Debian, when I run `sudo apt-get update` I get this error:

> W: Failed to fetch http://dl.bintray.com/dawidd6/neofetch/dists/jessie/Release  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

I'm running a Raspberry Pi 3 with the latest Raspbian release (based on Debian Jessie). Is there anything I'm missing? Maybe the package isn't build for my architecture?

I can always try to install using the manual installation but having it on the package manager is always better.

**Comment by iandrewt** [comment]
@dawidd6 only has `amd64` and `i386` support in his repository (despite Neofetch working on damn near anything, I ran it on a `armel` based QNAP NAS a few weeks ago to test it). Perhaps he can add support for other architectures to his repo

Neofetch is being added to the official Debian repositories soon though, so when Debian Stretch (and it's equivalent Raspbian version) comes out you should be able to install it without any additional repositories.

**Comment by dawidd6** [comment]
@vallovic @iandrewt i've investigated the problem. Here are some facts:

I'm providing neofetch debian package for "all" architectures, but now i see that apt doesn't look into "binary-all" directory. If there's no "binary-$arch", then apt throws error as above. The thing is, bintray makes only "amd64" and "i386" dirs, despite the fact, that package is marked: "Architecture: all" in control file as well in bintray itself.

The fix is simple. Just change this line in "/etc/apt/sources.list":
`deb http://dl.bintray.com/dawidd6/neofetch jessie main`
To this:
`deb [arch=all] http://dl.bintray.com/dawidd6/neofetch jessie main`

Tested on RPi2:
![screenshot_2016-11-24-00-27-30](https://cloud.githubusercontent.com/assets/9713907/20581967/de8b42b4-b1dc-11e6-8700-8619b84fa526.png)

**Comment by vallovic** [comment]
It worked, @dawidd6 ! 😄 Just installed, configured a bit and that's neofetch running on my RPi3. Thanks!

![screenshot 2016-11-24 00 26 00](https://cloud.githubusercontent.com/assets/115132/20582850/a76cc726-b1dc-11e6-8668-5520b75ba819.png)

**Comment by dawidd6** [comment]
Since 2.0 release this issue is resolved fully. There's no need to add `[arch=all]` anymore
