### ISSUE TITLE
Fetch doesn't display an image, only ASCII

### ISSUE THREAD

**Issue by terzag** [dylanaraps/fetch#62]
Using Ubuntu Mate 15.10. w3m (0.5.3+git20150811) and imagemagick (6.8.8.9) are installed from the repos.

When using Fetch with the --image option, providing either my personal wallpaper or a system one (tried /usr/share/backgrounds/warty-final-ubuntu.png), it doesn't display it, it still shows the distro ASCII logo.

**Comment by dylanaraps** [comment]
Thanks for opening this!

Add `set -x` to line `2` of the script and upload the output to pastebin / equiv.

**Comment by terzag** [comment]
Here is the output when running Fetch only: http://pastebin.com/ySQba7JL
Just in case, here is the output when setting the --image option manually: http://pastebin.com/Kc7g5nHG

**Comment by dylanaraps** [comment]
The script is failing to find the path to `w3m-img`.

**Comment by dylanaraps** [comment]
Where is it located on your system?

**Comment by terzag** [comment]
Oops, I only installed the w3m package, didn't see that there was a w3m-img package alongside in the repos.

Yet, after installing it, it doesn't really work better, as Fetch now doesn't display an image nor the ASCII logo. w3m-img isn't recognized as a valid command, which would explain that.

The w3m-img package installs the following files, according to Synaptic:
/usr
/usr/lib
/usr/lib/w3m
/usr/lib/w3m/w3mimgdisplay
/usr/share
/usr/share/doc
/usr/share/doc/w3m-img
/usr/share/doc/w3m-img/README.img.gz
/usr/share/doc/w3m-img/README.img.ja.gz
/usr/share/doc/w3m-img/changelog.Debian.gz
/usr/share/doc/w3m-img/copyright
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/w3m-img

Looks like the only installed binary is /usr/lib/w3m/w3mimgdisplay. Not sure it's normal?

**Comment by dylanaraps** [comment]
That's the normal location for it, can you show me the `set -x` output now?

**Comment by dylanaraps** [comment]
Also, what terminal emulator are you using?

**Comment by terzag** [comment]
New output: http://pastebin.com/AyWpj5DF

I'm using the default Mate terminal, which is "mate-terminal". Mate is a fork of Gnome 2 with softwares renamed so that they don't conflict with Gnome 2/3 packages. mate-terminal is basically gnome-terminal from Gnome 2 renamed and so on.

**Comment by dylanaraps** [comment]
The output shows that the script is running just fine now, try seeing if the image displays inside of `xterm` or `urxvt`.

This might be a terminal emulator issue, to make sure I'm also installing mate-terminal.

**Comment by terzag** [comment]
You're right: xterm shows an image.

**Comment by dylanaraps** [comment]
I've installed mate-terminal and the images seem work fine for me, weird.

![2016-02-09-213910_642x362_scrot](https://cloud.githubusercontent.com/assets/6799467/12913971/e3483842-cf75-11e5-8c94-73d83e03376b.png)

**Comment by terzag** [comment]
Oh, that's an issue with my system, then. If running directly the w3m web browser, I have the same problem: no images shown in Mate terminal but they do in xterm.

Guess we can close the issue there, I'll investigate on my side.

**Comment by dylanaraps** [comment]
Yeah, w3m-img doesn't work properly in some terminal emulators.

**Comment by terzag** [comment]
I might have found a clue. It looks like some terminal emulators display images with w3m only when there exists a $HOME/.mailcap file. It doesn't seem to be the case on my system (or Ubuntu in general, I guess). Can you confirm/infirm that on Arch you have such a file? That would explain why it works on your side.

**Comment by dylanaraps** [comment]
That file doesn't exist on my system.

**Comment by terzag** [comment]
Ok, wrong idea, then. Thanks for the update.
