### ISSUE TITLE
Recognising 3D controller GPUs

### ISSUE THREAD

**Issue by slaw0** [dylanaraps/fetch#65]
Multi GPU systems like laptops using nvidia optimus label the integrated GPU as the VGA device and the dedicated one as 3D controller:
`$ lspci | grep 3D`
`01:00.0 3D controller: NVIDIA Corporation GK107M [GeForce GT 750M] (rev a1)`

using `lspci | grep -F "VGA|3D"` should list every GPU. On the other hand I'm not sure about the formatting... Please update :)

**Comment by dylanaraps** [comment]
What I'll do is first check to see if there's a gpu starting with `3D controller` before falling back to checking `VGA controller`.

Give me 5 minutes. :)

**Comment by dylanaraps** [comment]
Fixed, please test it out.

**Comment by slaw0** [comment]
Works like a charm.
