### ISSUE TITLE
Strange output under tmux

### ISSUE THREAD

**Issue by tudurom** [dylanaraps/fetch#67]
![screenie](https://ipfs.pics/ipfs/QmfPMcudcUNLb1U5Md6eMusfJ5cSQsvotsew3mSHy4ofJ8)

**Comment by dylanaraps** [comment]
This is an issue with `w3m` and not fetch, `w3m` doesn't know about splits
etc and just prints from the top left corner of the window. You can use `--xoffset`
and `--yoffset` to manually move the image.

There's nothing we can do to fix this and it's not out bug so I'm going to close 
this issue.

(The colors going down the side look really cool btw)
