### ISSUE TITLE
Operating system support: Take 2

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/fetch#73]
These are the remaining OS we need to support to be at support parity
with Screenfetch. Again, I'm excluding distros that have been discontinued
as It's pointless to add support for them.

Anyone wanting to contribute, pick from the list below.

- Scientific Linux

**Comment by kelaun** [comment]
Downloading deepin and chapeau right now.

**Comment by kelaun** [comment]
Chapeau can't install in virtualbox, so this one can not be tested by me at least. Deepin is still downloading as their server is really slow (8+ hours download time).

**Comment by dylanaraps** [comment]
Thanks! :)

I'll cherrypick the Chapeau stuff from screenfetch.

**Comment by dylanaraps** [comment]
Added support for `Chapeau`. (Untested)

**Comment by kelaun** [comment]
I can't test deepin either. After 8+ hours of download, it failed on the last few bytes -_-'

**Comment by dylanaraps** [comment]
The same thing happened to me, the torrent is slow too...

**Comment by dylanaraps** [comment]
Actually, I just found a torrent with a bunch of seeders.

**Comment by dylanaraps** [comment]
I just added another distro to the list (Scientific Linux), the download for it just failed so
if you'd like to try that one out, be my guest.

I'm currently downloading Deepin.

**Comment by kelaun** [comment]
It's too big to download now, I might give it a try tomorrow though.

**Comment by dylanaraps** [comment]
There's a 700MB livecd among the 1.5GB isos.

http://ftp.scientificlinux.org/linux/scientific/7x/x86_64/iso/SL-72-x86_64-2016-02-03-LiveCD.iso

**Comment by dylanaraps** [comment]
Added support for `Deepin`.

**Comment by dylanaraps** [comment]
I'm downloading `Slackware` now.

Leaving this here as a reference:

- Counting packages: `ls -1 /var/log/packages | wc -l`

**Comment by dylanaraps** [comment]
Added support for `Slackware`.

**Comment by dylanaraps** [comment]
Added support for `Scientific Linux`.

**Comment by dylanaraps** [comment]
We now support all of the distros that Screenfetch supports.
