### ISSUE TITLE
Operating system support: Take 3

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/fetch#76]
We now support all of the Linux distros that Screenfetch supports!
(Excluding discontinued distros)

In this issue I'm aiming to support all of the `Distro Requests` in 
Screenfetch's issue tracker. These distros will be harder to add
support for due to availability and ease of use. 

Those wanting to contribute can pick a distro from the list below.

- ~~exherbo Linux~~
- coreos
- Red Hat Enterprise Linux 7 Beta
- ~~ChromeOS~~
- ~~ChromiumOS~~

**Comment by dylanaraps** [comment]
I'm downloading `exherbo Linux`.

**Comment by dylanaraps** [comment]
Added support for `exherno Linux`.

**Comment by kelaun** [comment]
Red Star OS is discontinued, right?
It was renamed to Estrella Roja and that one is discontinued.

**Comment by dylanaraps** [comment]
Removed it from the list, thanks.

**Comment by tudurom** [comment]
From what I know ChromeOS and ChromiumOS are based on Gentoo, so they should work.

**Comment by dylanaraps** [comment]
Yup, we still need to provide ascii art though. Having a look at 
Screenfetch, they're both named like this:

```sh
Chrome OS
Chromium OS
```

If we add the ascii art and colors then in theory it should work
just fine.

**Comment by dylanaraps** [comment]
Added `Chrome OS` ascii art and colors.

**Comment by tudurom** [comment]
Installing a VM right now.

**Comment by tudurom** [comment]
But here's a question: why would a CrOS user need fetch support?

**Comment by dylanaraps** [comment]
What do you mean by `CrOS`?

**Comment by tudurom** [comment]
ChromeOS.

**Comment by dylanaraps** [comment]
If it's simple to add support then why not? The more distros we 
support the more people will be able to use fetch and that's a
win.

**Comment by dylanaraps** [comment]
Chromium OS now uses the same ascii as ChromeOS as it's
difficult to add Chromium colors since they're various shades 
of blue and we're limited in the colors we can use.

**Comment by tudurom** [comment]
Well the majority of people are using ChromeOS and then ChromiumOS, so there's no problem. ChromiumOS is mostly used by enthusiasts to see what's the fuss about.

**Comment by dylanaraps** [comment]
I couldn't get Chromium OS to work in a virtual machine btw, 
if you also can't get it working then we'll still tick Chrome OS
and Chromium OS off the list. They should work just fine if
we compare our implementation to Screenfetch.

**Comment by dylanaraps** [comment]
Due to the difficulty in installing / obtaining the distros above
I'm going to close this issue. If anyone running these distros
wants support added then they'll need to open an issue them-
selves.

**Comment by chrisweeksnz** [comment]
I've had a crack at CoreOS... https://github.com/dylanaraps/neofetch/pull/832
