### ISSUE TITLE
ASCII image doesn't appear on OS X El Captain.

### ISSUE THREAD

**Issue by JaneSmith** [dylanaraps/fetch#78]
I installed the script as per the instructions on the web page, including this instruction:

> **El Captain:** `PREFIX=/usr/local make install`

When I run the command such as `fetch`, `fetch --image ascii`, `fetch --image ascii --ascii distro`, etc. it prints the system information without the fancy logo.

I'm no expert, but looking at the script's code it appears to get the ascii text from either /usr/share/fetch/ascii, or from the script's physical path. However, the files are actually located at /usr/local/share/fetch/ascii. Is this a bug, or did I do something wrong?

**Comment by dylanaraps** [comment]
Fixed, thanks for reporting this.

We'll need to eventually find a way for the script to use "$PREFIX"
from the makefile but for now I've added support for /usr/local.

You'll need to pull the latest master and rerun the makefile to get
the fix. Also you can just launch fetch with `fetch --ascii` to use 
your distros ascii art.

**Comment by JaneSmith** [comment]
That was fast - thanks! I updated to the latest version and can confirm that it works. :)

**Comment by dylanaraps** [comment]
Awesome! :)
