### ISSUE TITLE
--stdout is slower than default mode

### ISSUE THREAD

**Issue by tudurom** [dylanaraps/fetch#85]

**Comment by dylanaraps** [comment]
I can't reproduce this. Can you show me the output of `time fetch` and `time fetch --stdout`?

**Comment by dylanaraps** [comment]
Also give me the output of `time fetch --config off` and `time fetch --config off --stdout`

**Comment by tudurom** [comment]
Tomorrow. It's late here.

**Comment by dylanaraps** [comment]
Also, next time you open an issue please try to provide some info and some<br \>
steps to reproduce the issue.

**Comment by tudurom** [comment]
So, running `time fetch --config off --stdout birthday` takes 0m00.39s real and `time fetch --config of` 0m00.11s

**Comment by dylanaraps** [comment]
I can't seem to reproduce this, here's what I got:

```sh
# time fetch --config off
real	0m0.120s
user	0m0.063s
sys	    0m0.013s

# time fetch --config off --stdout birthday
real	0m0.031s
user	0m0.017s
sys	    0m0.003s
```

What's the **exact** output from these two commands? Are you sure you're not mixing up the decimal places?

**Comment by tudurom** [comment]
```bash
# time fetch --config off --stdout birthday
Fri 27 Nov 2015 12:39 AM        0m00.40s real     0m00.35s user     0m00.03s system
# time fetch --config off
    0m00.12s real     0m00.09s user     0m00.01s system
```

**Comment by dylanaraps** [comment]
I'm trying to reproduce this still...

- Does it happen with all info names (cpu, memory, disk etc) or is it only `birthday`?
- What's your shell?

**Comment by tudurom** [comment]
* This happens with all the info names
* I'm using mksh

**Comment by dylanaraps** [comment]
I simplified how we print the info for `--stdout arg arg`, try out the branch 
called `stdout` and let me know if it's any faster. (`--stdout` is the same)

**Comment by tudurom** [comment]
It's very fast now and it works! Thanks! I think you can merge it.

**Comment by dylanaraps** [comment]
I'm going to simplify `--stdout` with no args as well, then I'll merge it .:)

**Comment by dylanaraps** [comment]
I'm going to remove the "print all functions" feature when `--stdout` has no args.
There's no real use case for it and it's cluttering up the `info` and `prin` functions.
It's simpler and faster for the user to use `--stdout func func func`.

**Comment by dylanaraps** [comment]
Done.
