### ISSUE TITLE
gsettings crash on OS X

### ISSUE THREAD

**Issue by mkody** [dylanaraps/fetch#86]
Hi,
I've made a fresh install today on OS X El Capitan by cloning the repo and launching `PREFIX=/usr/local make install`.

Without touching the config or after some small changes, I keep having a popup showing up to say that `gsettings` crashed.
Here's the cash log: https://gist.github.com/mkody/15c142c2671830128127

**Comment by dylanaraps** [comment]
Add `set -x` to line 2 of the script and upload the output somewhere.

**Comment by dylanaraps** [comment]
Also, are you running X? (Xorg-server)

**Comment by dylanaraps** [comment]
I just pushed a change to master, try out the latest version.

**Comment by mkody** [comment]
Here's the output with `set -x`. https://gist.github.com/mkody/bd79fac7b1170e758a9a

No, I'm not running Xorg-server.
The latest version doesn't work too, I actually need to comment `info "Theme" theme` and `info "Icons" icons` in the config file to fix it.

**Comment by mkody** [comment]
(A bit unrelated, but I can't set an image since 6f115b3c19d7149f4c4ced2fdacf712883b5b322, but 0143724f6d4196afacaf6594dd668a6e6ce64702 works fine ([screenshot](https://cloud.githubusercontent.com/assets/843787/13184687/a218b80e-d73d-11e5-9bd2-0bdffadd8fe3.png)))

**Comment by dylanaraps** [comment]
I made some changes to image sizing and renamed the image_size value. You need
to change `image_size` from `half` to `auto`.

That should fix the image issues. I still can't wrap my head around the Theme issue,
what Screenfetch does is disable Theme, Font and Icons for all OS X versions. See
this issue from screenfetch:

https://github.com/KittyKatt/screenFetch/issues/82

The theme detection should only activate if the envar `$DISPLAY` has been set,
what's the output of this command?
```sh
echo "$DISPLAY"
```

**Comment by mkody** [comment]
Oh, looks like that there's [XQuartz](http://www.xquartz.org/) (and not X11 since [it was removed since 10.5](https://support.apple.com/en-us/HT201341)) running on my machine. Didn't saw it on the process list.
Output for `echo "$DISPLAY"`:
```
/private/tmp/com.apple.launchd.OMGwnzIqSw/org.macosforge.xquartz:0
```

>I don't want to resort to that as users running X under OS X won't be able to display
any theme information.

Opening the X session (by myself) and trying again in xterm is giving me the crash message anyways.

**Comment by dylanaraps** [comment]
I'll go ahead and disable the theme output on OS X, is the image problem still occuring?

**Comment by dylanaraps** [comment]
I've pushed a fix to master for the `gsettings` crash.

**Comment by mkody** [comment]
> is the image problem still occuring?

Nope, changing `image_size` to `auto` like you said fixed it.

And the gsettings crash isn't occurring anymore with latest master. :+1:

**Comment by dylanaraps** [comment]
Awesome :+1: 

I'll close this then!
