### ISSUE TITLE
The image no longer appears in tmux

### ISSUE THREAD

**Issue by tudurom** [dylanaraps/fetch#93]
I think this issue came from a recent commit.

**Comment by dylanaraps** [comment]
I need more info, 

- What's your terminal emulator?
- Does the image appear with `--config off`?
- What's the output with `set -x` added at line 2?

**Comment by tudurom** [comment]
* urxvt
* no
* https://gist.github.com/anonymous/de661b2e207daf6c60ae

**Comment by dylanaraps** [comment]
Change `image_size=half` to `image_size=auto`.

See this wiki page for all the breaking changes.

https://github.com/dylanaraps/fetch/wiki/Following-HEAD

**Comment by tudurom** [comment]
Still not working.

**Comment by tudurom** [comment]
When I try the version from the commit when I changed my screenshot, it works. This is all I know.

**Comment by dylanaraps** [comment]
What's the most recent commit it works on?

**Comment by tudurom** [comment]
I found the breaking one! 43239ecdc12bcaa8a1e5f0f1b438aaff6f3ebdbb

**Comment by dylanaraps** [comment]
What does this output?

```sh
printf "%b%s" '\033[14t'
```

**Comment by tudurom** [comment]
I know the bug. I'm running it inside of tmux and there is this line:

```bash
# If $img isn't a file or the terminal doesn't support xterm escape sequences,
+    # fallback to ascii mode.
+    if [ ! -f "$img" ] || [ -z "$term_height" ]; then
```

God knows how does tmux interpret those codes. You should add the old mechanism as well.

**Comment by dylanaraps** [comment]
I see, the escape code doesn't work inside of tmux.

**Comment by tudurom** [comment]
(btw I just posted my desktop over unixporn and I want to be sure that someone sees it before I got to bed. It's 2 am here but I'm just sitting there, listening to my music.)

**Comment by dylanaraps** [comment]
Looks awesome!

I'm going to try and get the escape sequence to work inside of tmux before I add
back the old behaviour.

**Comment by tudurom** [comment]
2 x Thanks!

**Comment by dylanaraps** [comment]
Fixed in tmux.

**Comment by tudurom** [comment]
Works perfectly, thanks!

**Comment by dylanaraps** [comment]
Awesome! :)

**Comment by argorain** [comment]
Hello, is there a way how to get images to appear in tmux? I am getting this message:
`Your terminal doesn't support \033[14t, falling back to ascii mode.`
Without tmux in same terminal images are showing well.
Thanks!

**Comment by dylanaraps** [comment]
Images work for me in tmux, can you give me some more details?

- tmux version
- neofetch version
- terminal emulator
- OS
- Distro
- A neofetch log file
    1. Run `neofetch -vv 2> neofetchlog`
    2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by argorain** [comment]
- tmux 1.9
- neofetch 1.8.1 from github
- gnome-terminal 3.14.1
- Linux
- Debian 8 Jessie
- Log is here: https://gist.github.com/argorain/bcea478da9dc79e1092086998e61cf7e

**Comment by dylanaraps** [comment]
I'm pretty sure that the issue is your tmux version being too old. Try updating tmux to the latest version to see if it works.

**Comment by argorain** [comment]
I tried it with latest tmux version (tmux 2.3) and still no luck. Maybe some underlaying lib...
Log is here: https://gist.github.com/argorain/770f66ec4f75751c3f2db6001f6d3bd8

**Comment by dylanaraps** [comment]
Neofetch uses `\033[14t` to get the terminal window size in pixels for image mode, for whatever reason your tmux install doesn't support this escape sequence so we fall back to ascii mode.

You might have something in your tmux config that's causing this issue to occur. Can you upload your tmux config somewhere so I can take a look?

If it is an issue with your config then we'll have to make a note in the wiki/readme about it.

**Comment by argorain** [comment]
I have no local confing, so everything is Debian's default.
I obtained that by this `tmux show -g > tmux_conf`
Result is here: https://gist.github.com/argorain/38a2252000269de576b7f7cc23ea3159

**Comment by dylanaraps** [comment]
Try and comment out this line:

```sh
terminal-overrides "*256col*:colors=256,xterm*:XT:Ms=\E]52;%p1%s;%p2%s\007:Cs=\E]12;%p1%s\007:Cr=\E]112\007:Ss=\E[%p1%d q:Se=\E[2 q,screen*:XT"
```

**Comment by argorain** [comment]
It is getting there from somewhere inside of tmux, because I have no `.tmux.conf` or `/etc/tmux.conf` or something else. I spent last two days trying to get rid of this line, but witout any luck... I'll try to write to tmux guys for help with that.

**Comment by argorain** [comment]
Oh, it works now! I forgot about one opened session so tmux server did not restarted when I tried open new tmux version. With blank tmux 2.3 it works, probably because of missing terminal overrides inside default config. 
Thanks a lot for help.

**Comment by dylanaraps** [comment]
Glad to hear it! :+1:

**Comment by broskees** [comment]
I have this issue with latest tmux config, but on mac using iterm. Outside of tmux session it works fine. Perhaps the fix for w3m doesn't apply to other image providers?

**Comment by TimeTravelPenguin** [comment]
I am also having this issue when calling `neofetch` on MacOS Sonoma 14.4. Here is my [tmux.conf](https://github.com/dylanaraps/neofetch/files/14721263/tmux.txt). When I call `neofetch` in iTerm2, there is no issue at all with any backend. However, within `tmux`, nothing seems to work. It only displays the Apple ASCII logo.

Using `neofetch --config config.conf -v 2> neofetch_log` gave [this output](https://pastebin.com/X6kXqUVN).
Using `neofetch --config config.conf -vv 2> neofetch_log` gave [this output](https://pastebin.com/A8QFbecg).
