### ISSUE TITLE
Custom info colors gets discarded when using screenfetch mode

### ISSUE THREAD

**Issue by tudurom** [dylanaraps/fetch#97]
[Screenshot with normal mode](https://u.teknik.io/bCryh.png).

[Screenshot with ascii mode](https://u.teknik.io/r5mWU.png).

[Logs](https://gist.github.com/tudurom/f8bc7018fb11c0ad33d5)

**Comment by dylanaraps** [comment]
Does this problem still occur with https://github.com/dylanaraps/fetch/pull/96 ?

**Comment by tudurom** [comment]
Nope.

**Comment by dylanaraps** [comment]
Awesome, I'll close this as it'll be fixed once we merge #96.

**Comment by dylanaraps** [comment]
The new color stuff is in master now.
